### ISSUE TITLE
Apollo error: Failed to fetch

### ISSUE THREAD

**Issue by CracerBeL** [twentyhq/twenty#2560]
I installed the applications using the official instructions, everything worked and went up right away, but when I go to the control page I get an error

I'm using this instruction: https://docs.twenty.com/contributor/local-setup/yarn-setup

Failed to fetch
ApolloError: Failed to fetch
    at new ApolloError (http://10.10.10.11:3001/static/js/bundle.js:464876:24)
    at Object.error (http://10.10.10.11:3001/static/js/bundle.js:463855:107)
    at notifySubscription (http://10.10.10.11:3001/static/js/bundle.js:571396:18)
    at onNotify (http://10.10.10.11:3001/static/js/bundle.js:571428:3)
    at SubscriptionObserver.error (http://10.10.10.11:3001/static/js/bundle.js:571470:5)
    at Object.error (http://10.10.10.11:3001/static/js/bundle.js:469165:39)
    at notifySubscription (http://10.10.10.11:3001/static/js/bundle.js:571396:18)
    at onNotify (http://10.10.10.11:3001/static/js/bundle.js:571428:3)
    at SubscriptionObserver.error (http://10.10.10.11:3001/static/js/bundle.js:571470:5)
    at http://10.10.10.11:3001/static/js/bundle.js:469205:23

I'm a complete 0 in this, so I would like to know what could go wrong?

![image](https://github.com/twentyhq/twenty/assets/111589292/bd1c0993-5087-4e49-9ecd-48dcf04953cf)

**Comment by FelixMalfait** [comment]
Hey sorry for the late reply on this. We somehow missed this issue 🤔.
This error is very common and generic so it's very hard to say. For example a common scenario could be that you have not started the server or that the server isn't running on the url that your frontend is expecting. 

Feel free to join https://twenty.com/discord for more direct support
