### ISSUE TITLE
Sync of standard objects failed with: QueryFailedError: function public.uuid_generate_v4() does not exist

### ISSUE THREAD

**Issue by netpoe** [twentyhq/twenty#4099]
## Bug Description

On the self-hosted installation, while running: `yarn nx database:init twenty-server`, I get this error:

```bash
Sync of standard objects failed with: QueryFailedError: function public.uuid_generate_v4() does not exist
    at PostgresQueryRunner.query (/Users/svpervnder/.cvvd/aufacicenta/twenty/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresQueryRunner.executeQueries (/Users/svpervnder/.cvvd/aufacicenta/twenty/node_modules/typeorm/query-runner/BaseQueryRunner.js:425:13)
    at async PostgresQueryRunner.createTable (/Users/svpervnder/.cvvd/aufacicenta/twenty/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:421:9)
    at async WorkspaceMigrationRunnerService.createTable (/Users/svpervnder/.cvvd/aufacicenta/twenty/packages/twenty-server/dist/src/workspace/workspace-migration-runner/workspace-migration-runner.service.js:74:9)
    at async WorkspaceMigrationRunnerService.handleTableChanges (/Users/svpervnder/.cvvd/aufacicenta/twenty/packages/twenty-server/dist/src/workspace/workspace-migration-runner/workspace-migration-runner.service.js:61:17)
    at async WorkspaceMigrationRunnerService.executeMigrationFromPendingMigrations (/Users/svpervnder/.cvvd/aufacicenta/twenty/packages/twenty-server/dist/src/workspace/workspace-migration-runner/workspace-migration-runner.service.js:40:17)
    at async WorkspaceSyncMetadataService.syncStandardObjectsAndFieldsMetadata (/Users/svpervnder/.cvvd/aufacicenta/twenty/packages/twenty-server/dist/src/workspace/workspace-sync-metadata/workspace-sync-metadata.service.js:52:13)
    at async DataSeedWorkspaceCommand.run (/Users/svpervnder/.cvvd/aufacicenta/twenty/packages/twenty-server/dist/src/database/commands/data-seed-dev-workspace.command.js:44:13)
    at async Command.<anonymous> (/Users/svpervnder/.cvvd/aufacicenta/twenty/node_modules/nest-commander/src/command-runner.service.js:156:24) {
  query: 'CREATE TABLE "workspace_1wgvd1injqtife6y4rvfbu3h5"."messageChannelMessageAssociation" ("id" uuid NOT NULL DEFAULT public.uuid_generate_v4(), "createdAt" timestamp NOT NULL DEFAULT now(), "updatedAt" timestamp NOT NULL DEFAULT now(), "deletedAt" timestamp, CONSTRAINT "PK_1a362709b248dbf0105195ba9a0" PRIMARY KEY ("id"))',
  parameters: undefined,
  driverError: error: function public.uuid_generate_v4() does not exist
      at /Users/svpervnder/.cvvd/aufacicenta/twenty/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/Users/svpervnder/.cvvd/aufacicenta/twenty/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
      at async PostgresQueryRunner.executeQueries (/Users/svpervnder/.cvvd/aufacicenta/twenty/node_modules/typeorm/query-runner/BaseQueryRunner.js:425:13)
      at async PostgresQueryRunner.createTable (/Users/svpervnder/.cvvd/aufacicenta/twenty/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:421:9)
      at async WorkspaceMigrationRunnerService.createTable (/Users/svpervnder/.cvvd/aufacicenta/twenty/packages/twenty-server/dist/src/workspace/workspace-migration-runner/workspace-migration-runner.service.js:74:9)
      at async WorkspaceMigrationRunnerService.handleTableChanges (/Users/svpervnder/.cvvd/aufacicenta/twenty/packages/twenty-server/dist/src/workspace/workspace-migration-runner/workspace-migration-runner.service.js:61:17)
      at async WorkspaceMigrationRunnerService.executeMigrationFromPendingMigrations (/Users/svpervnder/.cvvd/aufacicenta/twenty/packages/twenty-server/dist/src/workspace/workspace-migration-runner/workspace-migration-runner.service.js:40:17)
      at async WorkspaceSyncMetadataService.syncStandardObjectsAndFieldsMetadata (/Users/svpervnder/.cvvd/aufacicenta/twenty/packages/twenty-server/dist/src/workspace/workspace-sync-metadata/workspace-sync-metadata.service.js:52:13)
      at async DataSeedWorkspaceCommand.run (/Users/svpervnder/.cvvd/aufacicenta/twenty/packages/twenty-server/dist/src/database/commands/data-seed-dev-workspace.command.js:44:13) {
    length: 219,
    severity: 'ERROR',
    code: '42883',
    detail: undefined,
    hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
    position: '115',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_func.c',
    line: '629',
    routine: 'ParseFuncOrColumn'
  },
  length: 219,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
  position: '115',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_func.c',
  line: '629',
  routine: 'ParseFuncOrColumn'
}
TransactionNotStartedError: Transaction is not started yet, start transaction before committing or rolling it back.
    at PostgresQueryRunner.rollbackTransaction (/Users/svpervnder/.cvvd/aufacicenta/twenty/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:159:19)
    at WorkspaceSyncMetadataService.syncStandardObjectsAndFieldsMetadata (/Users/svpervnder/.cvvd/aufacicenta/twenty/packages/twenty-server/dist/src/workspace/workspace-sync-metadata/workspace-sync-metadata.service.js:56:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DataSeedWorkspaceCommand.run (/Users/svpervnder/.cvvd/aufacicenta/twenty/packages/twenty-server/dist/src/database/commands/data-seed-dev-workspace.command.js:44:13)
    at async Command.<anonymous> (/Users/svpervnder/.cvvd/aufacicenta/twenty/node_modules/nest-commander/src/command-runner.service.js:156:24)
    at async Command.parseAsync (/Users/svpervnder/.cvvd/aufacicenta/twenty/node_modules/commander/lib/command.js:936:5)
    at async CommandRunnerService.run (/Users/svpervnder/.cvvd/aufacicenta/twenty/node_modules/nest-commander/src/command-runner.service.js:196:9)
    at async CommandFactory.runApplication (/Users/svpervnder/.cvvd/aufacicenta/twenty/node_modules/nest-commander/src/command.factory.js:37:9)
    at async bootstrap (/Users/svpervnder/.cvvd/aufacicenta/twenty/packages/twenty-server/dist/src/command.js:24:5)
```

This is due to the `uuid-ossp` extension not being available in the `public` schema. 

I do see in `setup-db.ts` the following: 

```
await performQuery(
      'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"',
      'create extension "uuid-ossp"',
    );
```

and already made sure that the extension is enabled in my Postgres instance.

I also see this when the migrate command is running: 

```bash
> nx run twenty-server:typeorm migration:run -d src/database/typeorm/core/core.datasource
> twenty-server@0.3.1 typeorm
> npx ts-node ../../node_modules/typeorm/cli.js migration:run -d src/database/typeorm/core/core.datasource
query: SELECT * FROM current_schema()
query: CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
query: SELECT version();
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'core' AND "table_name" = '_typeorm_migrations'
query: SELECT * FROM "core"."_typeorm_migrations" "_typeorm_migrations" ORDER BY "id" DESC
No migrations are pending
```

I don't see the same for `public` though, which is the failing schema.

Is something missing in Typeorm for the `public` schema to also be enabled the extension?

**Comment by FelixMalfait** [comment]
I tried to reproduce but I wasn't able to.
Maybe try commands like` CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;` or `SELECT * FROM pg_extension WHERE extname='uuid-ossp';` to confirm your hypothesis that it's not created in the right schema? 
You should look for the column named extnamespace in the result set from pg_extension. This column contains the object identifier of the namespace (schema) where the extension is installed. To get the human-readable schema name, you need to join this with the pg_namespace system catalog using the OID.

**Comment by FelixMalfait** [comment]
I will be closing this since it didn't happen to anyone else and it didn't an answer following the previous comment. Thanks
