### ISSUE TITLE
Error when updating a custom field (text type) that contains "$$" somewhere in the string

### ISSUE THREAD

**Issue by ropoctl** [twentyhq/twenty#4830]
## Bug Description

I don't know how much of this is essential, but including the full repro.

I use graphql metadata mutation to create a custom field with field name "headline" on Person with a Text type. Then I use graphql mutation updatePerson to set headline on a person to 'Independent SEO Consultant $$ Hired by Top IT Companies and SaaS Startups| ASO and Digital Marketing Specialist'

```
operation: { name: 'Anonymous Operation', type: 'mutation' },
    document: 'mutation ($id: ID!, $data: PersonUpdateInput!) {\n' +                                                                                 
      '  updatePerson(id: $id, data: $data) {\n' +                                                                                                   
      '    id\n' +                                                                                                                                   
      '  }\n' +                                                                                                                                      
      '}',                                                                                                                                           
    user: undefined                                                                                                                                  
  }                                                                                                                                                  
  [
    QueryFailedError: syntax error at or near "Hired"
        at PostgresQueryRunner.query (/home/vagrant/twenty/src/driver/postgres/PostgresQueryRunner.ts:331:19)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at DataSource.query (/home/vagrant/twenty/src/data-source/DataSource.ts:536:20)
        at WorkspaceQueryRunnerService.execute (/home/vagrant/twenty/packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.service.ts:485:21)
        at WorkspaceQueryRunnerService.updateOne (/home/vagrant/twenty/packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-que
ry-runner.service.ts:286:20)
        at field.resolve (/home/vagrant/twenty/node_modules/@envelop/on-resolve/cjs/index.js:36:42)
        at /home/vagrant/twenty/node_modules/@envelop/core/cjs/orchestrator.js:383:27
        at YogaServer.getResultForParams (/home/vagrant/twenty/node_modules/graphql-yoga/cjs/server.js:304:26)
```

## Expected behavior

I would hope that the string escaping can sanitize $$

**Comment by FelixMalfait** [comment]
Sorry for the extremely slow reply. I tried to reproduce but couldn't so this has probably been fixed in the meantime.

<img width="451" alt="Screenshot 2024-09-11 at 17 31 14" src="https://github.com/user-attachments/assets/f75c8235-c5ea-422c-91b4-452b17e6f45e">
