### ISSUE TITLE
Getting an error when changing the theme locally

### ISSUE THREAD

**Issue by jwkjng** [twentyhq/twenty#4958]
## Bug Description

I've just set up the repo locally and run it for the first time. I was browsing around the site and ran into an issue with changing the appearance theme. I'm wondering if anyone else is able to reproduce this issue.

Example:

Go to Settings, Appearance, then change the theme from an existing one to any of the other ones. The server throws an error with the following message:

twenty/packages/twenty-server/src/engine/workspace-datasource/workspace-datasource.service.ts:128
      throw new Error(
            ^
Error: Error executing raw query for workspace 20202020-1c25-4d02-bf25-6aeccf7ea419: column "workspaceMemberId" specified more than once
    at WorkspaceDataSourceService.executeRawQuery (/Users/jasonjung/projects/clients/twenty/twenty/packages/twenty-server/src/engine/workspace-datasource/workspace-datasource.service.ts:128:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at EventRepository.insert (/Users/jasonjung/projects/clients/twenty/twenty/packages/twenty-server/src/modules/event/repositiories/event.repository.ts:30:5)
    at SaveEventToDbJob.handle (/Users/jasonjung/projects/clients/twenty/twenty/packages/twenty-server/src/engine/api/graphql/workspace-query-runner/jobs/save-event-to-db.job.ts:49:5)
    at SyncDriver.add (/Users/jasonjung/projects/clients/twenty/twenty/packages/twenty-server/src/engine/integrations/message-queue/drivers/sync.driver.ts:29:5)

Expected behavior

The theme can change without an error.

Technical inputs

As I was debugging through the codebase (I'm new to the codebase) but a recent change to the [Event Repository](https://github.com/twentyhq/twenty/commit/d876b400566ff53f9fe8282e64b25fbb051e60aa#diff-21dc2912113886974eb960e3d0db344df2058b8255ab6202cd7132167be41c70R57-R63) might be a potential cause? 

Essentially, the workspaceMemberId column is repeated twice in the Insert statement
```
INSERT INTO workspace_1wgvd1injqtife6y4rvfbu3h5."event"
      ("name", "properties", "workspaceMemberId", "workspaceMemberId")
      VALUES ($1, $2, $3, $4) [
  'updated.workspaceMember',
  { diff: { colorScheme: [Object] } },
  '20202020-0687-4c41-b707-ed1bfca972a7',
  '20202020-0687-4c41-b707-ed1bfca972a7'
```

Because the objectName variable in "${objectName}Id" is also workspaceMember, it seems to be causing this issue.

**Comment by FelixMalfait** [comment]
Good catch! Will raise a fix.

Was introduced here: https://github.com/twentyhq/twenty/pull/4898

**Comment by FelixMalfait** [comment]
Ok done! I think it shouldn't happen anymore! Let me know if it does

**Comment by jwkjng** [comment]
Confirming this fixed the issue. Thanks
