### ISSUE TITLE
Google Calendar only is missing scopes for proper OAuth

### ISSUE THREAD

**Issue by Flexusma** [twentyhq/twenty#5461]
## Bug Description

When using the current docker image, the oauth integration with google calendar does not include the required scopes for calendar access.

Scopes in oauth url: `email profile`. Without `https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar.events` twenty will not be able to access calendar data:

```
[Nest] 1  - 05/18/2024, 2:26:04 AM   ERROR [ExceptionsHandler] Insufficient Permission

Error: Insufficient Permission
    at Gaxios._request (/app/node_modules/gaxios/build/src/gaxios.js:140:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OAuth2Client.requestAsync (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:382:18)
    at async GoogleCalendarSyncService.getEventsFromGoogleCalendar (/app/packages/twenty-server/dist/src/modules/calendar/services/google-calendar-sync/google-calendar-sync.service.js:141:42)
    at async GoogleCalendarSyncService.startGoogleCalendarSync (/app/packages/twenty-server/dist/src/modules/calendar/services/google-calendar-sync/google-calendar-sync.service.js:69:43)
    at async GoogleCalendarSyncJob.handle (/app/packages/twenty-server/dist/src/modules/calendar/jobs/google-calendar-sync.job.js:32:9)
    at async SyncDriver.add (/app/packages/twenty-server/dist/src/engine/integrations/message-queue/drivers/sync.driver.js:19:9)
    at async GoogleAPIsService.enqueueSyncJobs (/app/packages/twenty-server/dist/src/engine/core-modules/auth/services/google-apis.service.js:93:13)
    at async GoogleAPIsService.refreshGoogleRefreshToken (/app/packages/twenty-server/dist/src/engine/core-modules/auth/services/google-apis.service.js:83:9)
    at async GoogleAPIsAuthController.googleAuthGetAccessToken (/app/packages/twenty-server/dist/src/engine/core-modules/auth/controllers/google-apis-auth.controller.js:49:9)
```
![grafik](https://github.com/twentyhq/twenty/assets/38422530/bc3c8874-ae74-4f55-be16-6704ffa2f1d5)

## Expected behavior

Expected `https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar.events` to be present in scope query.

## Technical inputs

I have not yet had a look into the corresponding code, but I susped there's some weird edgecase, that is being triggered to not include the correct scopes. GMAIL sync is DEACTIVATED in this install!

Current ENV:

```
TAG=latest
PG_DATABASE_HOST=db:5432
SERVER_URL=https://crm.xxx
SIGN_IN_PREFILLED=true
STORAGE_TYPE=local
ACCESS_TOKEN_SECRET=xxx
LOGIN_TOKEN_SECRET=xxx
REFRESH_TOKEN_SECRET=xxx
FILE_TOKEN_SECRET=xxx
POSTGRES_ADMIN_PASSWORD=xx
IS_SIGN_UP_DISABLED=true
STORAGE_LOCAL_PATH=storage
EMAIL_FROM_ADDRESS=no-reply@xxx
EMAIL_SYSTEM_ADDRESS=no-reply@xxx
EMAIL_FROM_NAME='twenty crm'
EMAIL_DRIVER=smtp
EMAIL_SMTP_HOST=xxx
EMAIL_SMTP_PORT=465
EMAIL_SMTP_USER=no-reply@xxx
EMAIL_SMTP_PASSWORD=xxx
ACCESS_TOKEN_EXPIRES_IN=3600m
LOGIN_TOKEN_EXPIRES_IN=3700m
AUTH_GOOGLE_ENABLED=true
AUTH_GOOGLE_CLIENT_ID=xxx.apps.googleusercontent.com
AUTH_GOOGLE_CLIENT_SECRET=GOCSPX-xxxxx
AUTH_GOOGLE_CALLBACK_URL=xxx/auth/google/redirect
AUTH_GOOGLE_APIS_CALLBACK_URL=xxx/auth/google-apis/get-access-token
CALENDAR_PROVIDER_GOOGLE_ENABLED: true
```

**Comment by Flexusma** [comment]
Addition: Including the mentioned scope in the oauth scopes correctly adds the calendar flow to the oauth process: 
![grafik](https://github.com/twentyhq/twenty/assets/38422530/44d6ad81-310b-40b8-bf84-2687ce4fc92e)

**Comment by crufter** [comment]
@Flexusma it seems like you have a colo `:` instead of `=` in this line:

```
CALENDAR_PROVIDER_GOOGLE_ENABLED: true
```

Maybe that is the source of your problems?

**Comment by FelixMalfait** [comment]
I'm sorry we didn't reply to this. I think @crufter is right. I'll close for now - please reopen if it was a different issue you've identified. Thanks
