### ISSUE TITLE
yarn nx run twenty-chrome-extension:"graphql:generate" not working on main

### ISSUE THREAD

**Issue by martmull** [twentyhq/twenty#5645]
## Error
```
Error 0: Unknown type "CompanyCreateInput".
      at /Users/charles/dev/twenty/twenty/packages/twenty-chrome-extension/src/graphql/company/mutations.ts:2:37
      Error 1: Cannot query field "createCompany" on type "Mutation".
      at /Users/charles/dev/twenty/twenty/packages/twenty-chrome-extension/src/graphql/company/mutations.ts:3:5
      Error 2: Unknown type "CompanyFilterInput".
      at /Users/charles/dev/twenty/twenty/packages/twenty-chrome-extension/src/graphql/company/queries.ts:2:30
      Error 3: Cannot query field "companies" on type "Query".
      at /Users/charles/dev/twenty/twenty/packages/twenty-chrome-extension/src/graphql/company/queries.ts:3:5
      Error 4: Unknown type "PersonCreateInput".
      at /Users/charles/dev/twenty/twenty/packages/twenty-chrome-extension/src/graphql/person/mutations.ts:2:36
      Error 5: Cannot query field "createPerson" on type "Mutation".
      at /Users/charles/dev/twenty/twenty/packages/twenty-chrome-extension/src/graphql/person/mutations.ts:3:5
      Error 6: Unknown type "PersonFilterInput".
      at /Users/charles/dev/twenty/twenty/packages/twenty-chrome-extension/src/graphql/person/queries.ts:2:29
      Error 7: Cannot query field "people" on type "Query".
      at /Users/charles/dev/twenty/twenty/packages/twenty-chrome-extension/src/graphql/person/queries.ts:3:5
```

**Comment by AdityaPimpalkar** [comment]
I'll look into this :D
