### ISSUE TITLE
Error in logs: QueryFailedError: column calendarChannel.contactAutoCreationPolicy does not exist

### ISSUE THREAD

**Issue by rob-luke** [twentyhq/twenty#6188]
Hi Twenty team.

Congratulations on the v0.21 release! The new features are fantastic!

After upgrading I am seeing the issue below. I hope this is the right place to report this. Maybe I upgraded incorrectly, if so, is there a way to fix this or upgrade correctly. Sharing publicly incase this helps others too.

## Description

After updating to v0.21.2 (or maybe this was happening before and I didn't notice it), I am getting the following error occuring in my logs and the calendar/mail functionality with google is no longer working. I am also now unable to remove my google account from the twenty settings page.

<details><summary>Log Error</summary>
<p>

```txt

query failed: SELECT "calendarChannel"."handle" AS "calendarChannel_handle", "calendarChannel"."connectedAccountId" AS "calendarChannel_connectedAccountId", "calendarChannel"."syncStatus" AS "calendarChannel_syncStatus", "calendarChannel"."syncStage" AS "calendarChannel_syncStage", "calendarChannel"."visibility" AS "calendarChannel_visibility", "calendarChannel"."isContactAutoCreationEnabled" AS "calendarChannel_isContactAutoCreationEnabled", "calendarChannel"."contactAutoCreationPolicy" AS "calendarChannel_contactAutoCreationPolicy", "calendarChannel"."isSyncEnabled" AS "calendarChannel_isSyncEnabled", "calendarChannel"."syncCursor" AS "calendarChannel_syncCursor", "calendarChannel"."syncStageStartedAt" AS "calendarChannel_syncStageStartedAt", "calendarChannel"."throttleFailureCount" AS "calendarChannel_throttleFailureCount", "calendarChannel"."id" AS "calendarChannel_id", "calendarChannel"."createdAt" AS "calendarChannel_createdAt", "calendarChannel"."updatedAt" AS "calendarChannel_updatedAt" FROM "workspace_6irr16qioalagnvc5ffeneuhx"."calendarChannel" "calendarChannel" WHERE (("calendarChannel"."isSyncEnabled" = $1) AND ("calendarChannel"."syncStage" = ANY($2))) -- PARAMETERS: [true,["FULL_CALENDAR_EVENT_LIST_FETCH_PENDING","PARTIAL_CALENDAR_EVENT_LIST_FETCH_PENDING"]]
error: error: column calendarChannel.contactAutoCreationPolicy does not exist
Exception Captured
  undefined
  [
    QueryFailedError: column calendarChannel.contactAutoCreationPolicy does not exist
        at PostgresQueryRunner.query (/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async SelectQueryBuilder.loadRawResults (/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
        at async SelectQueryBuilder.executeEntitiesAndRawResults (/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2040:26)
        at async SelectQueryBuilder.getRawAndEntities (/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
        at async SelectQueryBuilder.getMany (/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)
        at async WorkspaceRepository.find (/app/packages/twenty-server/dist/src/engine/twenty-orm/repository/workspace.repository.js:24:24)
        at async CalendarEventListFetchCronJob.handle (/app/packages/twenty-server/dist/src/modules/calendar/calendar-event-import-manager/crons/jobs/calendar-event-list-fetch.cron.job.js:48:38)
        at async MessageQueueExplorer.invokeProcessMethods (/app/packages/twenty-server/dist/src/engine/integrations/message-queue/message-queue.explorer.js:111:17)
        at async MessageQueueExplorer.handleProcessor (/app/packages/twenty-server/dist/src/engine/integrations/message-queue/message-queue.explorer.js:105:13) {
      query: 'SELECT "calendarChannel"."handle" AS "calendarChannel_handle", "calendarChannel"."connectedAccountId" AS "calendarChannel_connectedAccountId", "calendarChannel"."syncStatus" AS "calendarChannel_syncStatus", "calendarChannel"."syncStage" AS "calendarChannel_syncStage", "calendarChannel"."visibility" AS "calendarChannel_visibility", "calendarChannel"."isContactAutoCreationEnabled" AS "calendarChannel_isContactAutoCreationEnabled", "calendarChannel"."contactAutoCreationPolicy" AS "calendarChannel_contactAutoCreationPolicy", "calendarChannel"."isSyncEnabled" AS "calendarChannel_isSyncEnabled", "calendarChannel"."syncCursor" AS "calendarChannel_syncCursor", "calendarChannel"."syncStageStartedAt" AS "calendarChannel_syncStageStartedAt", "calendarChannel"."throttleFailureCount" AS "calendarChannel_throttleFailureCount", "calendarChannel"."id" AS "calendarChannel_id", "calendarChannel"."createdAt" AS "calendarChannel_createdAt", "calendarChannel"."updatedAt" AS "calendarChannel_updatedAt" FROM "workspace_6irr16qioalagnvc5ffeneuhx"."calendarChannel" "calendarChannel" WHERE (("calendarChannel"."isSyncEnabled" = $1) AND ("calendarChannel"."syncStage" = ANY($2)))',
      parameters: [ true, [Array] ],
      driverError: error: column calendarChannel.contactAutoCreationPolicy does not exist
          at /app/node_modules/pg/lib/client.js:526:17
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async PostgresQueryRunner.query (/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
          at async SelectQueryBuilder.loadRawResults (/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
          at async SelectQueryBuilder.executeEntitiesAndRawResults (/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2040:26)
          at async SelectQueryBuilder.getRawAndEntities (/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
          at async SelectQueryBuilder.getMany (/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)
          at async WorkspaceRepository.find (/app/packages/twenty-server/dist/src/engine/twenty-orm/repository/workspace.repository.js:24:24)
          at async CalendarEventListFetchCronJob.handle (/app/packages/twenty-server/dist/src/modules/calendar/calendar-event-import-manager/crons/jobs/calendar-event-list-fetch.cron.job.js:48:38)
          at async MessageQueueExplorer.invokeProcessMethods (/app/packages/twenty-server/dist/src/engine/integrations/message-queue/message-queue.explorer.js:111:17) {
        length: 140,
        severity: 'ERROR',
        code: '42703',
        detail: undefined,
        hint: undefined,
        position: '434',
        internalPosition: undefined,
        internalQuery: undefined,
        where: undefined,
        schema: undefined,
        table: undefined,
        column: undefined,
        dataType: undefined,
        constraint: undefined,
        file: 'parse_relation.c',
        line: '3656',
        routine: 'errorMissingColumn'
      },
      length: 140,
      severity: 'ERROR',
      code: '42703',
      detail: undefined,
      hint: undefined,
      position: '434',
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: undefined,
      table: undefined,
      column: undefined,
      dataType: undefined,
      constraint: undefined,
      file: 'parse_relation.c',
      line: '3656',
      routine: 'errorMissingColumn'
    }
  ]
  ```

</p>
</details> 

## Expected behavior

- Able to disconnect google account from the twenty instance
- Mail/Calendar sync adds details to CRM
- No errors in the logs

## Technical inputs

- I am self hosting using docker compose
- Everything has been working reliably for several months (love Twenty!)
- I just upgraded to v0.21.2 from v0.20. Perhaps I missed some commands that needed to be run to update the database?

---

Thank you for your great software and for the assistance

**Comment by FelixMalfait** [comment]
Hey @rob-luke thanks a lot for the report, sorry for that. I just answered on #6189, if you don't mind I will close this issue so we can keep the discussion in one place (even though you created this issue first, I saw it after the other one)
