### ISSUE TITLE
deleting a connected gmail account fails

### ISSUE THREAD

**Issue by aficiomaquinas** [twentyhq/twenty#6189]
I was finally able to deploy my portainer twenty. fantastic work guys and thank you very much for putting this together i look forward to using this for a long time!

## Bug Description

![Screenshot_161_070924_082435_PM](https://github.com/twentyhq/twenty/assets/304489/accaf982-46d2-4851-a139-1774d65512ff)
![Screenshot_070924_082529_PM](https://github.com/twentyhq/twenty/assets/304489/eea80c26-bd10-4ca9-b65a-3f86da1139e2)
![Screenshot_162_070924_082605_PM](https://github.com/twentyhq/twenty/assets/304489/7393c331-e9e0-4a30-97b9-b743741542a0)
![Screenshot_163_070924_082649_PM](https://github.com/twentyhq/twenty/assets/304489/aa29a62a-35b1-4230-b2fe-fb29405c285c)

i'm having a bit of a problem with the gmail sync... the account connected successfully, the worker showed to be syncing messages, but on the front end i don't see the email tab and i don't see any contacts. i tried to delete the connected account and re-connect it, but upon clicking 'remove account' i get:

request (copied as curl from chrome dev tools)
```
curl "https://twenty.mydomain.com/graphql" ^
  -H "accept: */*" ^
  -H "accept-language: en-US,en;q=0.9,es-MX;q=0.8,es;q=0.7" ^
  -H "authorization: Bearer xxxxxxxxxxxx" ^
  -H "cache-control: no-cache" ^
  -H "content-type: application/json" ^
  -H ^"cookie: xxxxxxxxxxxxxxxxx" ^
  -H "origin: https://twenty.mydomain.com/" ^
  -H "pragma: no-cache" ^
  -H "priority: u=1, i" ^
  -H "referer: https://twenty.mydomain.com//settings/accounts" ^
  -H ^"sec-ch-ua: ^\^"Not/A)Brand^\^";v=^\^"8^\^", ^\^"Chromium^\^";v=^\^"126^\^", ^\^"Google Chrome^\^";v=^\^"126^\^"^" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H ^"sec-ch-ua-platform: ^\^"Windows^\^"^" ^
  -H "sec-fetch-dest: empty" ^
  -H "sec-fetch-mode: cors" ^
  -H "sec-fetch-site: same-origin" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" ^
  -H "x-schema-version: 1" ^
  --data-raw ^"^{^\^"operationName^\^":^\^"DeleteOneConnectedAccount^\^",^\^"variables^\^":^{^\^"idToDelete^\^":^\^"579268cd-6d6b-492c-b67f-xxxxxxxxx^\^"^},^\^"query^\^":^\^"mutation DeleteOneConnectedAccount(^$idToDelete: ID^!) ^{^\^\n  deleteConnectedAccount(id: ^$idToDelete) ^{^\^\n    id^\^\n    __typename^\^\n  ^}^\^\n^}^\^"^}^"
```

response:
```
{"errors":[{"message":"QueryFailedError","extensions":{"code":"INTERNAL_SERVER_ERROR","response":"column messageChannel.contactAutoCreationPolicy does not exist"}}],"data":{"deleteConnectedAccount":null}}
```

worker log:
```
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] FileUploadModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] CacheModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] CacheStorageModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] DataSourceModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] NestjsQueryTypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] WorkspaceMigrationModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] WorkspaceCacheVersionModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] WorkspaceDataSourceModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] RemoteTableRelationsModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] ObjectMetadataRepositoryModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] ObjectMetadataRepositoryModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] ObjectMetadataRepositoryModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] ObjectMetadataRepositoryModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] ObjectMetadataRepositoryModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] ObjectMetadataRepositoryModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] ObjectMetadataRepositoryModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] ObjectMetadataRepositoryModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] ObjectMetadataRepositoryModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] WorkspaceMigrationRunnerModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TwentyORMCoreModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] EmailAliasManagerModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] GoogleAPIRefreshAccessTokenModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] CalendarCommonModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] CreateContactModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] CreateCompanyModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TimelineActivityModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TwentyORMModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TwentyORMModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TwentyORMModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TwentyORMModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TwentyORMModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TwentyORMModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TwentyORMModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] MessagingCommonModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] AutoCompaniesAndContactsCreationModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TimelineJobModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] RecordPositionBackfillModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] WorkspaceHealthModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] GoogleCalendarDriverModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] AutoCompaniesAndContactsCreationJobModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] WorkspaceQueryRunnerJobModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] MessagingMessageCleanerModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] CalendarEventCleanerModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] CalendarEventParticipantManagerModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] MessagingBlocklistManagerModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] CalendarBlocklistManagerModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] NestjsQueryGraphQLModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] ObjectMetadataModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] NestjsQueryTypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] MessageParticipantManagerModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] NestjsQueryTypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] NestjsQueryTypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] NestjsQueryTypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] NestjsQueryTypeOrmModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] NestjsQueryGraphQLModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] FeatureFlagModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] UserWorkspaceModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] KeyValuePairModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] WorkspaceSyncMetadataModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] NestjsQueryGraphQLModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] MessagingMonitoringModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] CalendarEventImportManagerModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] MessagingGmailDriverModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] WorkspaceManagerModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] MessagingImportManagerModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] DataSeedDemoWorkspaceModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] NestjsQueryGraphQLModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] JobsModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] OnboardingModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] BillingModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] WorkspaceModule dependencies initialized
[Nest] 33  - 07/10/2024, 1:58:41 AM     LOG [InstanceLoader] UserModule dependencies initialized
[Nest] 33  - 07/10/2024, 2:00:05 AM     LOG [MessagingMessageListFetchJob] Fetching partial message list for workspace f5ed3fa9-53b6-4e17-81fa-abdff5e5b197 and messageChannelId e16898fa-5a24-4a12-9811-01a9437ee437
[Nest] 33  - 07/10/2024, 2:00:06 AM     LOG [MessagingGmailPartialMessageListFetchService] Partial message list import done with history 2773405 and nothing to update for workspace f5ed3fa9-53b6-4e17-81fa-abdff5e5b197 and account 579268cd-6d6b-492c-b67f-1a07651e2652
[Nest] 33  - 07/10/2024, 2:05:09 AM     LOG [MessagingMessageListFetchJob] Fetching partial message list for workspace f5ed3fa9-53b6-4e17-81fa-abdff5e5b197 and messageChannelId e16898fa-5a24-4a12-9811-01a9437ee437
[Nest] 33  - 07/10/2024, 2:05:10 AM     LOG [MessagingGmailPartialMessageListFetchService] Partial message list import done with history 2773405 and nothing to update for workspace f5ed3fa9-53b6-4e17-81fa-abdff5e5b197 and account 579268cd-6d6b-492c-b67f-1a07651e2652
[Nest] 33  - 07/10/2024, 2:10:07 AM     LOG [MessagingMessageListFetchJob] Fetching partial message list for workspace f5ed3fa9-53b6-4e17-81fa-abdff5e5b197 and messageChannelId e16898fa-5a24-4a12-9811-01a9437ee437
[Nest] 33  - 07/10/2024, 2:10:07 AM     LOG [MessagingGmailPartialMessageListFetchService] Partial message list import done with history 2773405 and nothing to update for workspace f5ed3fa9-53b6-4e17-81fa-abdff5e5b197 and account 579268cd-6d6b-492c-b67f-1a07651e2652
[Nest] 33  - 07/10/2024, 2:15:07 AM     LOG [MessagingMessageListFetchJob] Fetching partial message list for workspace f5ed3fa9-53b6-4e17-81fa-abdff5e5b197 and messageChannelId e16898fa-5a24-4a12-9811-01a9437ee437
[Nest] 33  - 07/10/2024, 2:15:08 AM     LOG [MessagingGmailPartialMessageListFetchService] Partial message list import done with history 2773405 and nothing to update for workspace f5ed3fa9-53b6-4e17-81fa-abdff5e5b197 and account 579268cd-6d6b-492c-b67f-1a07651e2652
[Nest] 33  - 07/10/2024, 2:20:07 AM     LOG [MessagingMessageListFetchJob] Fetching partial message list for workspace f5ed3fa9-53b6-4e17-81fa-abdff5e5b197 and messageChannelId e16898fa-5a24-4a12-9811-01a9437ee437
[Nest] 33  - 07/10/2024, 2:20:08 AM     LOG [MessagingGmailPartialMessageListFetchService] Partial message list import done with history 2773405 and nothing to update for workspace f5ed3fa9-53b6-4e17-81fa-abdff5e5b197 and account 579268cd-6d6b-492c-b67f-1a07651e2652
[Nest] 33  - 07/10/2024, 2:25:05 AM     LOG [MessagingMessageListFetchJob] Fetching partial message list for workspace f5ed3fa9-53b6-4e17-81fa-abdff5e5b197 and messageChannelId e16898fa-5a24-4a12-9811-01a9437ee437
[Nest] 33  - 07/10/2024, 2:25:06 AM     LOG [MessagingGmailPartialMessageListFetchService] Partial message list import done with history 2773405 and nothing to update for workspace f5ed3fa9-53b6-4e17-81fa-abdff5e5b197 and account 579268cd-6d6b-492c-b67f-1a07651e2652
```

server log:
```
query failed: SELECT "messageChannel"."visibility" AS "messageChannel_visibility", "messageChannel"."connectedAccountId" AS "messageChannel_connectedAccountId", "messageChannel"."handle" AS "messageChannel_handle", "messageChannel"."type" AS "messageChannel_type", "messageChannel"."isContactAutoCreationEnabled" AS "messageChannel_isContactAutoCreationEnabled", "messageChannel"."contactAutoCreationPolicy" AS "messageChannel_contactAutoCreationPolicy", "messageChannel"."excludeNonProfessionalEmails" AS "messageChannel_excludeNonProfessionalEmails", "messageChannel"."excludeGroupEmails" AS "messageChannel_excludeGroupEmails", "messageChannel"."isSyncEnabled" AS "messageChannel_isSyncEnabled", "messageChannel"."syncCursor" AS "messageChannel_syncCursor", "messageChannel"."syncedAt" AS "messageChannel_syncedAt", "messageChannel"."syncStatus" AS "messageChannel_syncStatus", "messageChannel"."syncStage" AS "messageChannel_syncStage", "messageChannel"."syncStageStartedAt" AS "messageChannel_syncStageStartedAt", "messageChannel"."throttleFailureCount" AS "messageChannel_throttleFailureCount", "messageChannel"."id" AS "messageChannel_id", "messageChannel"."createdAt" AS "messageChannel_createdAt", "messageChannel"."updatedAt" AS "messageChannel_updatedAt" FROM "workspace_ek5247m991i2yr03431oilbx3"."messageChannel" "messageChannel" WHERE (("messageChannel"."connectedAccountId" = $1)) -- PARAMETERS: ["579268cd-6d6b-492c-b67f-1a07651e2652"]
error: error: column messageChannel.contactAutoCreationPolicy does not exist
Exception Captured
  {
    operation: { name: 'DeleteOneConnectedAccount', type: 'mutation' },
    document: 'mutation DeleteOneConnectedAccount($idToDelete: ID!) {\n' +
      '  deleteConnectedAccount(id: $idToDelete) {\n' +
      '    id\n' +
      '    __typename\n' +
      '  }\n' +
      '}',
    user: User {
      id: '8e2577f8-9c0f-43b3-be1e-a99495dd7b27',
      firstName: '',
      lastName: '',
      email: 'victor@example.com',
      defaultAvatarUrl: null,
      emailVerified: false,
      disabled: false,
      passwordHash: '$2b$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      canImpersonate: false,
      createdAt: 2024-07-05T03:30:31.282Z,
      updatedAt: 2024-07-05T03:30:31.282Z,
      deletedAt: null,
      defaultWorkspaceId: 'f5ed3fa9-53b6-4e17-81fa-abdff5e5b197',
      passwordResetToken: null,
      passwordResetTokenExpiresAt: null,
      defaultWorkspace: Workspace {
        id: 'f5ed3fa9-53b6-4e17-81fa-abdff5e5b197',
        domainName: '',
        displayName: 'example.com',
        logo: 'workspace-logo/original/37baea89-38f5-4633-a9b7-c67daea532e1.png',
        inviteHash: 'f8098b9c-e8f0-42bf-b233-825458b8c898',
        deletedAt: null,
        createdAt: 2024-07-05T03:30:31.272Z,
        updatedAt: 2024-07-10T02:01:19.029Z,
        allowImpersonation: false
      }
    }
  }
  [
    QueryFailedError: column messageChannel.contactAutoCreationPolicy does not exist
        at PostgresQueryRunner.query (/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async SelectQueryBuilder.loadRawResults (/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
        at async SelectQueryBuilder.executeEntitiesAndRawResults (/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2040:26)
        at async SelectQueryBuilder.getRawAndEntities (/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
        at async SelectQueryBuilder.getMany (/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)
        at async WorkspaceRepository.findBy (/app/packages/twenty-server/dist/src/engine/twenty-orm/repository/workspace.repository.js:33:24)
        at async ConnectedAccountDeleteOnePreQueryHook.execute (/app/packages/twenty-server/dist/src/modules/connected-account/query-hooks/connected-account/connected-account-delete-one.pre-query.hook.js:33:33)
        at async WorkspaceQueryHookExplorer.handleHook (/app/packages/twenty-server/dist/src/engine/api/graphql/workspace-query-runner/workspace-query-hook/workspace-query-hook.explorer.js:58:13)
        at async WorkspaceQueryHookService.executePreQueryHooks (/app/packages/twenty-server/dist/src/engine/api/graphql/workspace-query-runner/workspace-query-hook/workspace-query-hook.service.js:31:13) {
      path: [ 'deleteConnectedAccount' ],
      locations: [ [Object] ],
      extensions: [Object: null prototype] {}
    }
  ]
```

**Comment by aficiomaquinas** [comment]
seems like #6188, but better to be confirmed by someone who knows the codebase

**Comment by FelixMalfait** [comment]
Hey @aficiomaquinas thanks for the report! The upgrade process from one version to another is still very poorly documented. It seems like you need to run the "sync metadata" command to update the standard object to match their definition in code, this will run a migration and create the column. 

`yarn command:prod workspace:sync-metadata -w WORKSPACE_ID -f`

We really need to improve this upgrade mechanism @charlesBochet could someone create a small page in the documentation even if imperfect it's better than nothing? Even I don't know the process

**Comment by rob-luke** [comment]
@FelixMalfait thanks, this worked!

**Comment by FelixMalfait** [comment]
Great! Closing but let me know if I should reopen @aficiomaquinas

**Comment by aficiomaquinas** [comment]
@FelixMalfait It worked for me too, i was able to delete the gmail account. Is it normal that I still don't have an Email tab? I read somewhere that the object had to be created manually but I don't remember where and it's not on the docs.

**Comment by aficiomaquinas** [comment]
@FelixMalfait I really don't know the codebase at all so it will be difficult for me to trace the origin of this bug. I'll reset the install and go from there, if I encounter something I'll open up another issue. Thank you very much.
