### ISSUE TITLE
ApolloError UserInputError - Cannot Delete Custom field

### ISSUE THREAD

**Issue by mnbro** [twentyhq/twenty#6197]
## Bug Description

I try to delete a custom field but I receive:
`ApolloError UserInputError`
`
ApolloError:UserInputError
 at new t (/assets/index-JGIdMgsI.js:325:152)
 at ? (/assets/index-JGIdMgsI.js:329:75936)
 at d (/assets/index-JGIdMgsI.js:324:8526)
 at ? (/assets/index-JGIdMgsI.js:324:8441)
 at new Promise (<anonymous>)
 at Object.then (/assets/index-JGIdMgsI.js:324:8408)
 at Object.next (/assets/index-JGIdMgsI.js:324:8536)
 at jFe (/assets/index-JGIdMgsI.js:324:1934)
 at pW (/assets/index-JGIdMgsI.js:324:2346)
 at t.next (/assets/index-JGIdMgsI.js:324:2869)
 at ? (/assets/index-JGIdMgsI.js:324:8326)
 at Array.forEach (<anonymous>)
 at P9 (/assets/index-JGIdMgsI.js:324:8295)
 at Object.next (/assets/index-JGIdMgsI.js:324:9289)
 at jFe (/assets/index-JGIdMgsI.js:324:1934)
 at pW (/assets/index-JGIdMgsI.js:324:2346)
 at t.next (/assets/index-JGIdMgsI.js:324:2869)
 at Object.next (/assets/index-JGIdMgsI.js:994:23683)
 at jFe (/assets/index-JGIdMgsI.js:324:1934)
 at pW (/assets/index-JGIdMgsI.js:324:2346)
 at t.next (/assets/index-JGIdMgsI.js:324:2869)
 at jFe (/assets/index-JGIdMgsI.js:324:1934)
 at pW (/assets/index-JGIdMgsI.js:324:2346)
 at t.next (/assets/index-JGIdMgsI.js:324:2869)
 at Object.onNext [as next] (/assets/index-JGIdMgsI.js:994:24898)
 at jFe (/assets/index-JGIdMgsI.js:324:1934)
 at pW (/assets/index-JGIdMgsI.js:324:2346)
 at t.next (/assets/index-JGIdMgsI.js:324:2869)
 at ? (/assets/index-JGIdMgsI.js:994:29354)
`

## Expected behavior

Be able to delete Custom Field

**Comment by FelixMalfait** [comment]
Hey, do you have the backend error, if you open the network tab and find the failing graphql query? Thanks!

**Comment by FelixMalfait** [comment]
Related: https://github.com/twentyhq/twenty/issues/4841
@ijreilly how should we move forward? It's actually possible to delete a composite field? Thanks 🙏

**Comment by prateekj117** [comment]
@ijreilly I think we can close this issue as this was resolved as part of https://github.com/twentyhq/twenty/pull/6320

**Comment by ijreilly** [comment]
Sorry @FelixMalfait and @mnbro I did not see the notifications for this one. 
Yes, it can be closed, thanks a lot @prateekj117 !
