### ISSUE TITLE
Stuck on partially blank screen after upgrade from 22.0 to 23.0

### ISSUE THREAD

**Issue by StefanoMarchesi** [twentyhq/twenty#6554]
After upgrading from version 22.0 to 23.0 and running :
yarn database:migrate:prod
yarn command:prod workspace:sync-metadata -f 
yarn command:prod upgrade-0.23

I can not do anything because the screen is partially blank (no objects)
<img width="2045" alt="Screenshot 2024-08-06 alle 15 09 14" src="https://github.com/user-attachments/assets/180b427d-0069-47d2-8538-21093f1f55a5">

seraching for an object has the same problem
<img width="2048" alt="Screenshot 2024-08-06 alle 15 12 29" src="https://github.com/user-attachments/assets/dc0899cf-00b1-46ad-89d7-f5d28889086e">

The stetting page seems to work fine but there is a running loader before every menu section
<img width="2045" alt="Screenshot 2024-08-06 alle 15 13 54" src="https://github.com/user-attachments/assets/cc891a70-7446-4700-b201-c88de69f75c6">

If i try to add a field to an existing object i get this errror
<img width="2050" alt="Screenshot 2024-08-06 alle 15 15 22" src="https://github.com/user-attachments/assets/4b8cbf68-3bfe-4959-b55c-3218446229eb">

I have some error in console
`Failed to load resource: the server responded with a status of 404 ()
/object/person/00d87…a17d-1fd2b5635783:1  Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
2index-J6xhINk2.js:5517  useFindManyRecords for "timelineActivities" error : ApolloError: GraphQL errors on timelineActivity: {"message":"cannot pass more than 100 arguments to a function"}
console.error @ index-J6xhINk2.js:5517
index-J6xhINk2.js:5517  TypeError: Cannot read properties of null (reading 'edges')
    at CC (index-J6xhINk2.js:1285:2640)
    at index-J6xhINk2.js:1356:184
    at Array.map (<anonymous>)
    at gon (index-J6xhINk2.js:1356:168)
    at ysn (index-J6xhINk2.js:1372:1417)
    at vde (index-J6xhINk2.js:6:19643)
    at Sne (index-J6xhINk2.js:8:3166)
    at OPe (index-J6xhINk2.js:8:45176)
    at MPe (index-J6xhINk2.js:8:40078)
    at V8t (index-J6xhINk2.js:8:40001)
console.error @ index-J6xhINk2.js:5517
index-J6xhINk2.js:5517  React Router caught the following error during render TypeError: Cannot read properties of null (reading 'edges')
    at CC (index-J6xhINk2.js:1285:2640)
    at index-J6xhINk2.js:1356:184
    at Array.map (<anonymous>)
    at gon (index-J6xhINk2.js:1356:168)
    at ysn (index-J6xhINk2.js:1372:1417)
    at vde (index-J6xhINk2.js:6:19643)
    at Sne (index-J6xhINk2.js:8:3166)
    at OPe (index-J6xhINk2.js:8:45176)
    at MPe (index-J6xhINk2.js:8:40078)
    at V8t (index-J6xhINk2.js:8:40001) Object
console.error @ index-J6xhINk2.js:5517`

**Comment by StefanoMarchesi** [comment]
Hey, I had some error but i've re run the commands and now I have no error:

yarn command:prod workspace:sync-metadata -f :
`[Nest] 406  - 08/06/2024, 12:46:08 PM   ERROR [CompositeColumnActionFactory] Current property not found for altered property: primaryLinkLabel
[Nest] 406  - 08/06/2024, 12:46:08 PM   ERROR [WorkspaceSyncMetadataService] Sync of standard objects failed with:
[Nest] 406  - 08/06/2024, 12:46:08 PM   ERROR [WorkspaceSyncMetadataService] Error: Current property not found for altered property: primaryLinkLabel`

yarn command:prod upgrade-0.23:
`[Nest] 493  - 08/06/2024, 12:46:46 PM     LOG [UpdateActivitiesCommand] Running command on workspace e38b5b3f-8b09-424b-b78f-f552ef391e5c failed
[Nest] 493  - 08/06/2024, 12:46:46 PM   ERROR [UpdateActivitiesCommand] Migration failed for workspace e38b5b3f-8b09-424b-b78f-f552ef391e5c: No metadata for "note" was found., EntityMetadataNotFoundError: No metadata for "note" was found.
    at WorkspaceDataSource.getMetadata (/app/node_modules/typeorm/data-source/DataSource.js:304:19)
    at get metadata [as metadata] (/app/node_modules/typeorm/repository/Repository.js:15:40)
    at WorkspaceRepository.create (/app/node_modules/typeorm/repository/Repository.js:52:41)
    at updateActivities (/app/packages/twenty-server/dist/src/database/commands/upgrade-version/0-23/0-23-update-activities.command.js:68:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UpdateActivitiesCommand.executeWithQueryRunner (/app/packages/twenty-server/dist/src/database/commands/upgrade-version/0-23/0-23-update-activities.command.js:279:21)
    at async UpdateActivitiesCommand.sharedBoilerplate (/app/packages/twenty-server/dist/src/database/commands/upgrade-version/0-23/0-23-update-activities.command.js:257:21)
    at async UpgradeTo0_23Command.run (/app/packages/twenty-server/dist/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.command.js:43:9)
    at async Command.<anonymous> (/app/node_modules/nest-commander/src/command-runner.service.js:156:24)
    at async Command.parseAsync (/app/node_modules/commander/lib/command.js:936:5)`

**Comment by StefanoMarchesi** [comment]
I've jus a warning:

**Comment by lhjt** [comment]
I can also confirm issues trying to migrate from 0.22.0 to 0.23.0.

### `yarn command:prod workspace:sync-metadata -f`
```
error: error: duplicate key value violates unique constraint "IndexOnNameObjectMetadataIdAndWorkspaceIdUnique"
[Nest] 157  - 08/06/2024, 5:01:43 PM   ERROR [WorkspaceSyncMetadataService] Sync of standard objects failed with:
[Nest] 157  - 08/06/2024, 5:01:43 PM   ERROR [WorkspaceSyncMetadataService] QueryFailedError: duplicate key value violates unique constraint "IndexOnNameObjectMetadataIdAndWorkspaceIdUnique"
```

### `yarn command:prod upgrade-0.23`
```
error: error: duplicate key value violates unique constraint "IndexOnNameObjectMetadataIdAndWorkspaceIdUnique"
[Nest] 196  - 08/06/2024, 5:07:45 PM   ERROR [WorkspaceSyncMetadataService] Sync of standard objects failed with:
[Nest] 196  - 08/06/2024, 5:07:45 PM   ERROR [WorkspaceSyncMetadataService] QueryFailedError: duplicate key value violates unique constraint "IndexOnNameObjectMetadataIdAndWorkspaceIdUnique"
[Nest] 196  - 08/06/2024, 5:07:45 PM     LOG [SyncWorkspaceMetadataCommand] Finished synchronizing all active workspaces (1 workspaces).
[Nest] 196  - 08/06/2024, 5:07:45 PM     LOG [UpdateActivitiesCommand] Running command on 1 workspaces
[Nest] 196  - 08/06/2024, 5:07:45 PM     LOG [UpdateActivitiesCommand] Running command on workspace c532f267-57ec-4041-96bd-451714b0b8e6 failed
[Nest] 196  - 08/06/2024, 5:07:45 PM   ERROR [UpdateActivitiesCommand] Migration failed for workspace c532f267-57ec-4041-96bd-451714b0b8e6: No metadata for "note" was found., EntityMetadataNotFoundError: No metadata for "note" was found.
    at WorkspaceDataSource.getMetadata (/app/node_modules/typeorm/data-source/DataSource.js:304:19)
    at get metadata [as metadata] (/app/node_modules/typeorm/repository/Repository.js:15:40)
    at WorkspaceRepository.create (/app/node_modules/typeorm/repository/Repository.js:52:41)
    at updateActivities (/app/packages/twenty-server/dist/src/database/commands/upgrade-version/0-23/0-23-update-activities.command.js:68:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UpdateActivitiesCommand.executeWithQueryRunner (/app/packages/twenty-server/dist/src/database/commands/upgrade-version/0-23/0-23-update-activities.command.js:279:21)
    at async UpdateActivitiesCommand.sharedBoilerplate (/app/packages/twenty-server/dist/src/database/commands/upgrade-version/0-23/0-23-update-activities.command.js:257:21)
    at async UpgradeTo0_23Command.run (/app/packages/twenty-server/dist/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.command.js:43:9)
    at async Command.<anonymous> (/app/node_modules/nest-commander/src/command-runner.service.js:156:24)
    at async Command.parseAsync (/app/node_modules/commander/lib/command.js:936:5)
```

**Comment by Bonapara** [comment]
Closing this issue, we will improve the migration in the coming versions
