### ISSUE TITLE
Upgrade from 0.22.1 to 0.23.0 missing metadata for task

### ISSUE THREAD

**Issue by richardwiden** [twentyhq/twenty#6578]
## Bug Description

bash <(curl -sL https://git.new/20)
change TAG to 0.22.1
docker compose up
login to app and create user, workspace, task and opportunity
docker compose down
change tag to 0.23.0
docker compose up
docker exec -it twenty-server-1 yarn database:migrate:prod
docker exec -it twenty-server-1 yarn command:prod workspace:sync-metadata -f
docker exec -it twenty-server-1 yarn command:prod upgrade-0.23

**yarn command:prod workspace:sync-metadata -f**
```
[Nest] 190  - 08/08/2024, 8:41:03 AM   ERROR [CompositeColumnActionFactory] Current property not found for altered property: primaryLinkLabel
[Nest] 190  - 08/08/2024, 8:41:03 AM   ERROR [WorkspaceSyncMetadataService] Sync of standard objects failed with:
[Nest] 190  - 08/08/2024, 8:41:03 AM   ERROR [WorkspaceSyncMetadataService] Error: Current property not found for altered property: primaryLinkLabel
[Nest] 190  - 08/08/2024, 8:41:03 AM     LOG [SyncWorkspaceMetadataCommand] Finished synchronizing all active workspaces (1 workspaces). 
```

**yarn command:prod upgrade-0.23**
```
Nest] 276  - 08/08/2024, 8:41:36 AM     LOG [UpdateActivitiesCommand] Running command on 1 workspaces
[Nest] 276  - 08/08/2024, 8:41:36 AM     LOG [UpdateActivitiesCommand] Running command on workspace 10112282-f691-4005-b9d4-c51fe2d4b6c4 failed
[Nest] 276  - 08/08/2024, 8:41:36 AM   ERROR [UpdateActivitiesCommand] Migration failed for workspace 10112282-f691-4005-b9d4-c51fe2d4b6c4: No metadata for "task" was found., EntityMetadataNotFoundError: No metadata for "task" was found.
    at WorkspaceDataSource.getMetadata (/app/node_modules/typeorm/data-source/DataSource.js:304:19)
    at get metadata [as metadata] (/app/node_modules/typeorm/repository/Repository.js:15:40)
    at WorkspaceRepository.create (/app/node_modules/typeorm/repository/Repository.js:52:41)
    at updateActivities (/app/packages/twenty-server/dist/src/database/commands/upgrade-version/0-23/0-23-update-activities.command.js:110:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UpdateActivitiesCommand.executeWithQueryRunner (/app/packages/twenty-server/dist/src/database/commands/upgrade-version/0-23/0-23-update-activities.command.js:279:21)
    at async UpdateActivitiesCommand.sharedBoilerplate (/app/packages/twenty-server/dist/src/database/commands/upgrade-version/0-23/0-23-update-activities.command.js:257:21)
    at async UpgradeTo0_23Command.run (/app/packages/twenty-server/dist/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.command.js:43:9)
    at async Command.<anonymous> (/app/node_modules/nest-commander/src/command-runner.service.js:156:24)
    at async Command.parseAsync (/app/node_modules/commander/lib/command.js:936:5)
```

## Expected behavior

For database created in version 0.X.0 to be able to upgrade to X+1 cleanly

**Comment by Bonapara** [comment]
@richardwiden did you manage to upgrade?

**Comment by richardwiden** [comment]
> @richardwiden did you manage to upgrade?

This was a general issue that was reproduceable without our data. Our data had other issues that may or may not have been resolved - I am no longer involved with the project so I can't say whether that was fixed or not.
