### ISSUE TITLE
Deleted member of workspace still has access to workspace

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6675]
**Preconditions:** 2 workspaces and 2 members (1st workspace both members, 2nd workspace only 1 member) best to test on self-hosted instance as all preconditions are checked (account `tim@apple.dev`)

**Scenario:**
1. Log in as user with access to both workspaces (`tim@apple.dev`)
2. In workspace with 2 members go to Settings > Profile and delete account
3. Log in again

**Actual:** User can still access the workspace where the account was earlier deleted (although all tabs will be empty)
![image](https://github.com/user-attachments/assets/15c50d64-e8c3-43cc-8174-ee5278b5f1e6)

**Expected:** User should only have access to these workspaces where it's account is active

**Logs:**
```
[Nest] 737321  - 08/19/2024, 4:56:46 PM   ERROR [ExceptionsHandler] WorkspaceMember not found
AssertionError [ERR_ASSERTION]: WorkspaceMember not found
    at UserService.deleteUser (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/core-modules/user/services/user.service.ts:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at target (/home/user/Desktop/projects/twenty/node_modules/@nestjs/core/helpers/external-context-creator.js:74:28)
    at Object.deleteUser (/home/user/Desktop/projects/twenty/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
    at field.resolve (/home/user/Desktop/projects/twenty/node_modules/@envelop/on-resolve/cjs/index.js:36:42)
    at /home/user/Desktop/projects/twenty/node_modules/@envelop/core/cjs/orchestrator.js:383:27
    at YogaServer.getResultForParams (/home/user/Desktop/projects/twenty/node_modules/graphql-yoga/cjs/server.js:304:26)
    at YogaServer.handle (/home/user/Desktop/projects/twenty/node_modules/graphql-yoga/cjs/server.js:77:29)
Exception Captured
  {
    operation: { name: 'DeleteUserAccount', type: 'mutation' },
    document: 'mutation DeleteUserAccount {\n  deleteUser {\n    id\n    __typename\n  }\n}',
    user: User {
      id: 'af5f365a-023f-4b17-9e3c-753058b3d390',
      firstName: '',
      lastName: '',
      email: 'test@apple.dev',
      defaultAvatarUrl: null,
      emailVerified: false,
      disabled: false,
      passwordHash: '$2b$10$HFVkhlDgGWNeorIyYeTyhOpA5UjYUaMmV3GR55/HVJOHNFST2/yIa',
      canImpersonate: false,
      createdAt: 2024-08-19T14:48:15.592Z,
      updatedAt: 2024-08-19T14:48:15.592Z,
      deletedAt: null,
      defaultWorkspaceId: '3b8e6458-5fc1-4e63-8563-008ccddaa6db',
      defaultWorkspace: Workspace {
        id: '3b8e6458-5fc1-4e63-8563-008ccddaa6db',
        domainName: 'twenty.dev',
        displayName: 'Twenty',
        logo: 'https://twentyhq.github.io/placeholder-images/workspaces/twenty-logo.png',
        inviteHash: 'twenty.dev-invite-hash',
        deletedAt: null,
        createdAt: 2024-08-19T14:45:24.935Z,
        updatedAt: 2024-08-19T14:45:24.935Z,
        allowImpersonation: true,
        activationStatus: 'ACTIVE'
      }
    }
  }
  [
    AssertionError [ERR_ASSERTION]: WorkspaceMember not found
        at UserService.deleteUser (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/core-modules/user/services/user.service.ts:99:11)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at target (/home/user/Desktop/projects/twenty/node_modules/@nestjs/core/helpers/external-context-creator.js:74:28)
        at Object.deleteUser (/home/user/Desktop/projects/twenty/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
        at field.resolve (/home/user/Desktop/projects/twenty/node_modules/@envelop/on-resolve/cjs/index.js:36:42)
        at /home/user/Desktop/projects/twenty/node_modules/@envelop/core/cjs/orchestrator.js:383:27
        at YogaServer.getResultForParams (/home/user/Desktop/projects/twenty/node_modules/graphql-yoga/cjs/server.js:304:26)
        at YogaServer.handle (/home/user/Desktop/projects/twenty/node_modules/graphql-yoga/cjs/server.js:77:29) {
      path: undefined,
      locations: undefined,
      extensions: {
        code: 'INTERNAL_SERVER_ERROR',
        response: 'WorkspaceMember not found'
      }
    }
  ]
[Nest] 737321  - 08/19/2024, 4:56:54 PM     LOG [WorkspaceQueryRunnerService] query time: 53.544122993946075 ms on query favorite
[Nest] 737321  - 08/19/2024, 4:56:54 PM     LOG [WorkspaceQueryRunnerService] query time: 55.263083040714264 ms on query view
[Nest] 737321  - 08/19/2024, 4:57:01 PM   ERROR [ExceptionsHandler] WorkspaceMember not found
AssertionError [ERR_ASSERTION]: WorkspaceMember not found
    at UserService.deleteUser (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/core-modules/user/services/user.service.ts:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at target (/home/user/Desktop/projects/twenty/node_modules/@nestjs/core/helpers/external-context-creator.js:74:28)
    at Object.deleteUser (/home/user/Desktop/projects/twenty/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
    at field.resolve (/home/user/Desktop/projects/twenty/node_modules/@envelop/on-resolve/cjs/index.js:36:42)
    at /home/user/Desktop/projects/twenty/node_modules/@envelop/core/cjs/orchestrator.js:383:27
    at YogaServer.getResultForParams (/home/user/Desktop/projects/twenty/node_modules/graphql-yoga/cjs/server.js:304:26)
    at YogaServer.handle (/home/user/Desktop/projects/twenty/node_modules/graphql-yoga/cjs/server.js:77:29)
Exception Captured
  {
    operation: { name: 'DeleteUserAccount', type: 'mutation' },
    document: 'mutation DeleteUserAccount {\n  deleteUser {\n    id\n    __typename\n  }\n}',
    user: User {
      id: 'af5f365a-023f-4b17-9e3c-753058b3d390',
      firstName: '',
      lastName: '',
      email: 'test@apple.dev',
      defaultAvatarUrl: null,
      emailVerified: false,
      disabled: false,
      passwordHash: '$2b$10$HFVkhlDgGWNeorIyYeTyhOpA5UjYUaMmV3GR55/HVJOHNFST2/yIa',
      canImpersonate: false,
      createdAt: 2024-08-19T14:48:15.592Z,
      updatedAt: 2024-08-19T14:48:15.592Z,
      deletedAt: null,
      defaultWorkspaceId: '3b8e6458-5fc1-4e63-8563-008ccddaa6db',
      defaultWorkspace: Workspace {
        id: '3b8e6458-5fc1-4e63-8563-008ccddaa6db',
        domainName: 'twenty.dev',
        displayName: 'Twenty',
        logo: 'https://twentyhq.github.io/placeholder-images/workspaces/twenty-logo.png',
        inviteHash: 'twenty.dev-invite-hash',
        deletedAt: null,
        createdAt: 2024-08-19T14:45:24.935Z,
        updatedAt: 2024-08-19T14:45:24.935Z,
        allowImpersonation: true,
        activationStatus: 'ACTIVE'
      }
    }
  }
  [
    AssertionError [ERR_ASSERTION]: WorkspaceMember not found
        at UserService.deleteUser (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/core-modules/user/services/user.service.ts:99:11)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at target (/home/user/Desktop/projects/twenty/node_modules/@nestjs/core/helpers/external-context-creator.js:74:28)
        at Object.deleteUser (/home/user/Desktop/projects/twenty/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
        at field.resolve (/home/user/Desktop/projects/twenty/node_modules/@envelop/on-resolve/cjs/index.js:36:42)
        at /home/user/Desktop/projects/twenty/node_modules/@envelop/core/cjs/orchestrator.js:383:27
        at YogaServer.getResultForParams (/home/user/Desktop/projects/twenty/node_modules/graphql-yoga/cjs/server.js:304:26)
        at YogaServer.handle (/home/user/Desktop/projects/twenty/node_modules/graphql-yoga/cjs/server.js:77:29) {
      path: undefined,
      locations: undefined,
      extensions: {
        code: 'INTERNAL_SERVER_ERROR',
        response: 'WorkspaceMember not found'
      }
    }
  ]
```

**Comment by Bonapara** [comment]
Is this the same issue we had with "Test Charles," which is still online but breaks when we try to access it, @charlesBochet?

**Comment by charlesBochet** [comment]
Might be, I think the userWorkspace might not be deleted
Tagging this one as good first issue

**Comment by Bonapara** [comment]
/oss.gg 300

**Comment by charlesBochet** [comment]
/oss.gg 300

**Comment by Khaan25** [comment]
@Bonapara Can I work on this? Could you assign me?

**Comment by Khaan25** [comment]
@charlesBochet, My other PR is under review, I would like to work on this?

**Comment by Hitarthsheth07** [comment]
Hey @charlesBochet I tried reproducing this issue but it is working correcly in my PC. 

I am using wsl ubuntu in windows:

https://www.loom.com/share/0015201cd04043a0bd3b6e35634857fe?sid=d2e8273c-20e3-40ce-bf3d-51657495dc08

Please close this if it's solved...

**Comment by BOHEUS** [comment]
I'm closing this issue as it's solved by one of merged PRs
