### ISSUE TITLE
Unable to start using app in production (app.twenty.com) after subscribing

### ISSUE THREAD

**Issue by ad-elias** [twentyhq/twenty#6838]
## Bug Description

I'm not able to start using the app after trying to pay with Stripe. It looked like the payment went through on Stripe while paying, but I don't see any charge on my bank account. I signed in using Google single sign-on.

1.
<img width="1582" alt="bug-1" src="https://github.com/user-attachments/assets/219b5c9c-9466-44c1-9444-fc6138081c94">
2.
<img width="1582" alt="bug-2" src="https://github.com/user-attachments/assets/05a126e9-14c2-41a3-95af-9193b3398226">
3.
<img width="1582" alt="bug-3" src="https://github.com/user-attachments/assets/b8e956df-9855-46dd-a051-07bb28facf5f">

Clicking anything takes me back to screenshot 1.

## Expected behavior

Should be able to start using the app.

## Technical inputs

Error in console:

```
Uncaught (in promise) ApolloError: Data source metadata not found for workspace 9e3706f2-bde0-42b5-8c1e-ce5425754318
    at new t (index-BNuAfbf2.js:279:152)
    at index-BNuAfbf2.js:283:64676
    at d (index-BNuAfbf2.js:278:8526)
    at index-BNuAfbf2.js:278:8441
    at new Promise (<anonymous>)
    at Object.then (index-BNuAfbf2.js:278:8408)
    at Object.next (index-BNuAfbf2.js:278:8536)
    at C$e (index-BNuAfbf2.js:278:1934)
    at xG (index-BNuAfbf2.js:278:2346)
    at t.next (index-BNuAfbf2.js:278:2869)
    at index-BNuAfbf2.js:278:8326
    at Array.forEach (<anonymous>)
    at C6 (index-BNuAfbf2.js:278:8295)
    at Object.next (index-BNuAfbf2.js:278:9289)
    at C$e (index-BNuAfbf2.js:278:1934)
    at xG (index-BNuAfbf2.js:278:2346)
    at t.next (index-BNuAfbf2.js:278:2869)
    at Object.next (index-BNuAfbf2.js:957:23736)
    at C$e (index-BNuAfbf2.js:278:1934)
    at xG (index-BNuAfbf2.js:278:2346)
    at t.next (index-BNuAfbf2.js:278:2869)
    at C$e (index-BNuAfbf2.js:278:1934)
    at xG (index-BNuAfbf2.js:278:2346)
    at t.next (index-BNuAfbf2.js:278:2869)
    at C$e (index-BNuAfbf2.js:278:1934)
    at xG (index-BNuAfbf2.js:278:2346)
    at t.next (index-BNuAfbf2.js:278:2869)
    at index-BNuAfbf2.js:957:28512
```

**Comment by ad-elias** [comment]
@BOHEUS 

1. Ok, done 👍
2. Sent it to @FelixMalfait on Discord already

**Comment by FelixMalfait** [comment]
Thanks for the report @ad-elias!
