### ISSUE TITLE
Object metadata item "task" cannot be found in an array of 28 elements

### ISSUE THREAD

**Issue by toorusr** [twentyhq/twenty#7005]
## Bug Description

Just upgraded my account and am hit with this error. Different browser doesn't help either.

## Expected behavior

Should be able to just use the software.

## Technical inputs

```
Unexpected Application Error!
Object metadata item "task" cannot be found in an array of 28 elements
Error: Object metadata item "task" cannot be found in an array of 28 elements
    at cn (https://app.twenty.com/assets/index-Dt42-Pvt.js:1364:1188)
    at Op (https://app.twenty.com/assets/index-Dt42-Pvt.js:2278:807)
    at Tx (https://app.twenty.com/assets/index-Dt42-Pvt.js:4982:1064)
    at MSr (https://app.twenty.com/assets/index-Dt42-Pvt.js:6241:5683)
    at qae (https://app.twenty.com/assets/index-Dt42-Pvt.js:6:17091)
    at UX (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:3159)
    at vRe (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:45092)
    at mRe (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:40005)
    at gyt (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:39928)
    at RN (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:39776)
    at tQ (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:36109)
    at Fme (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:36916)
    at wv (https://app.twenty.com/assets/index-Dt42-Pvt.js:6:3302)
    at https://app.twenty.com/assets/index-Dt42-Pvt.js:8:34423

```

Console:
```

index-Dt42-Pvt.js:5672 Dj: Object metadata item "note" cannot be found in an array of 28 elements
    at cn (https://app.twenty.com/assets/index-Dt42-Pvt.js:1364:1188)
    at Pa (https://app.twenty.com/assets/index-Dt42-Pvt.js:1616:5902)
    at Ven (https://app.twenty.com/assets/index-Dt42-Pvt.js:1703:633)
    at qae (https://app.twenty.com/assets/index-Dt42-Pvt.js:6:17091)
    at UX (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:3159)
    at vRe (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:45092)
    at mRe (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:40005)
    at gyt (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:39928)
    at RN (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:39776)
    at tQ (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:36109)
    at Fme (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:36916)
    at wv (https://app.twenty.com/assets/index-Dt42-Pvt.js:6:3302)
    at https://app.twenty.com/assets/index-Dt42-Pvt.js:8:34423
console.error @ index-Dt42-Pvt.js:5672Understand this error
index-Dt42-Pvt.js:5672 React Router caught the following error during render Dj: Object metadata item "note" cannot be found in an array of 28 elements
    at cn (https://app.twenty.com/assets/index-Dt42-Pvt.js:1364:1188)
    at Pa (https://app.twenty.com/assets/index-Dt42-Pvt.js:1616:5902)
    at Ven (https://app.twenty.com/assets/index-Dt42-Pvt.js:1703:633)
    at qae (https://app.twenty.com/assets/index-Dt42-Pvt.js:6:17091)
    at UX (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:3159)
    at vRe (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:45092)
    at mRe (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:40005)
    at gyt (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:39928)
    at RN (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:39776)
    at tQ (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:36109)
    at Fme (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:36916)
    at wv (https://app.twenty.com/assets/index-Dt42-Pvt.js:6:3302)
    at https://app.twenty.com/assets/index-Dt42-Pvt.js:8:34423 Object
console.error @ index-Dt42-Pvt.js:5672Understand this error
index-Dt42-Pvt.js:5672 Dj: Object metadata item "task" cannot be found in an array of 28 elements
    at cn (https://app.twenty.com/assets/index-Dt42-Pvt.js:1364:1188)
    at Op (https://app.twenty.com/assets/index-Dt42-Pvt.js:2278:807)
    at Tx (https://app.twenty.com/assets/index-Dt42-Pvt.js:4982:1064)
    at MSr (https://app.twenty.com/assets/index-Dt42-Pvt.js:6241:5683)
    at qae (https://app.twenty.com/assets/index-Dt42-Pvt.js:6:17091)
    at UX (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:3159)
    at vRe (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:45092)
    at mRe (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:40005)
    at gyt (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:39928)
    at RN (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:39776)
    at tQ (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:36109)
    at Fme (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:36916)
    at wv (https://app.twenty.com/assets/index-Dt42-Pvt.js:6:3302)
    at https://app.twenty.com/assets/index-Dt42-Pvt.js:8:34423
console.error @ index-Dt42-Pvt.js:5672Understand this error
index-Dt42-Pvt.js:5672 React Router caught the following error during render Dj: Object metadata item "task" cannot be found in an array of 28 elements
    at cn (https://app.twenty.com/assets/index-Dt42-Pvt.js:1364:1188)
    at Op (https://app.twenty.com/assets/index-Dt42-Pvt.js:2278:807)
    at Tx (https://app.twenty.com/assets/index-Dt42-Pvt.js:4982:1064)
    at MSr (https://app.twenty.com/assets/index-Dt42-Pvt.js:6241:5683)
    at qae (https://app.twenty.com/assets/index-Dt42-Pvt.js:6:17091)
    at UX (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:3159)
    at vRe (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:45092)
    at mRe (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:40005)
    at gyt (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:39928)
    at RN (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:39776)
    at tQ (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:36109)
    at Fme (https://app.twenty.com/assets/index-Dt42-Pvt.js:8:36916)
    at wv (https://app.twenty.com/assets/index-Dt42-Pvt.js:6:3302)
    at https://app.twenty.com/assets/index-Dt42-Pvt.js:8:34423 Object
```

**Comment by Bonapara** [comment]
Hi @toorusr, can you ask on our Discord #help channel? Thanks!
