### ISSUE TITLE
When modifying record's details, error is thrown

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7452]
**Scenario:**
1. Log in
2. Go to Companies tab (or any other object tab)
3. Try modifying record's data

**Actual:** Error is thrown
[Screencast From 2024-10-05 18-54-30.webm](https://github.com/user-attachments/assets/0c1ea105-197f-4637-9403-4619c49715fb)

**Expected:** No error must be thrown

Error:
```
Exception Captured
  {
    operation: { name: 'UpdateOnePerson', type: 'mutation' },
    document: 'mutation UpdateOnePerson($idToUpdate: ID!, $input: PersonUpdateInput!) {\n' +
      '  updatePerson(id: $idToUpdate, data: $input) {\n' +
      '    __typename\n' +
      '    emails {\n' +
      '      primaryEmail\n' +
      '      additionalEmails\n' +
      '      __typename\n' +
      '    }\n' +
      '    noteTargets {\n' +
      '      edges {\n' +
      '        node {\n' +
      '          __typename\n' +
      '          id\n' +
      '          aId\n' +
      '          companyId\n' +
      '          personId\n' +
      '          rocketId\n' +
      '          deletedAt\n' +
      '          createdAt\n' +
      '          opportunityId\n' +
      '          noteId\n' +
      '          updatedAt\n' +
      '        }\n' +
      '        __typename\n' +
      '      }\n' +
      '      __typename\n' +
      '    }\n' +
      '    linkedinLink {\n' +
      '      primaryLinkUrl\n' +
      '      primaryLinkLabel\n' +
      '      secondaryLinks\n' +
      '      __typename\n' +
      '    }\n' +
      '    attachments {\n' +
      '      edges {\n' +
      '        node {\n' +
      '          __typename\n' +
      '          type\n' +
      '          noteId\n' +
      '          updatedAt\n' +
      '          opportunityId\n' +
      '          rocketId\n' +
      '          deletedAt\n' +
      '          createdAt\n' +
      '          name\n' +
      '          fullPath\n' +
      '          activityId\n' +
      '          aId\n' +
      '          personId\n' +
      '          companyId\n' +
      '          authorId\n' +
      '          id\n' +
      '          taskId\n' +
      '        }\n' +
      '        __typename\n' +
      '      }\n' +
      '      __typename\n' +
      '    }\n' +
      '    intro\n' +
      '    favorites {\n' +
      '      edges {\n' +
      '        node {\n' +
      '          __typename\n' +
      '          updatedAt\n' +
      '          rocketId\n' +
      '          workspaceMemberId\n' +
      '          personId\n' +
      '          noteId\n' +
      '          id\n' +
      '          deletedAt\n' +
      '          aId\n' +
      '          opportunityId\n' +
      '          createdAt\n' +
      '          companyId\n' +
      '          position\n' +
      '          viewId\n' +
      '          taskId\n' +
      '        }\n' +
      '        __typename\n' +
      '      }\n' +
      '      __typename\n' +
      '    }\n' +
      '    taskTargets {\n' +
      '      edges {\n' +
      '        node {\n' +
      '          __typename\n' +
      '          personId\n' +
      '          updatedAt\n' +
      '          deletedAt\n' +
      '          aId\n' +
      '          createdAt\n' +
      '          rocketId\n' +
      '          id\n' +
      '          opportunityId\n' +
      '          companyId\n' +
      '          taskId\n' +
      '        }\n' +
      '        __typename\n' +
      '      }\n' +
      '      __typename\n' +
      '    }\n' +
      '    whatsapp {\n' +
      '      primaryPhoneNumber\n' +
      '      primaryPhoneCountryCode\n' +
      '      additionalPhones\n' +
      '      __typename\n' +
      '    }\n' +
      '    performanceRating\n' +
      '    companyId\n' +
      '    company {\n' +
      '      __typename\n' +
      '      createdBy {\n' +
      '        source\n' +
      '        workspaceMemberId\n' +
      '        name\n' +
      '        __typename\n' +
      '      }\n' +
      '      workPolicy\n' +
      '      idealCustomerProfile\n' +
      '      name\n' +
      '      position\n' +
      '      id\n' +
      '      address {\n' +
      '        addressStreet1\n' +
      '        addressStreet2\n' +
      '        addressCity\n' +
      '        addressState\n' +
      '        addressCountry\n' +
      '        addressPostcode\n' +
      '        addressLat\n' +
      '        addressLng\n' +
      '        __typename\n' +
      '      }\n' +
      '      introVideo {\n' +
      '        primaryLinkUrl\n' +
      '        primaryLinkLabel\n' +
      '        secondaryLinks\n' +
      '        __typename\n' +
      '      }\n' +
      '      domainName {\n' +
      '        primaryLinkUrl\n' +
      '        primaryLinkLabel\n' +
      '        secondaryLinks\n' +
      '        __typename\n' +
      '      }\n' +
      '      linkedinLink {\n' +
      '        primaryLinkUrl\n' +
      '        primaryLinkLabel\n' +
      '        secondaryLinks\n' +
      '        __typename\n' +
      '      }\n' +
      '      deletedAt\n' +
      '      employees\n' +
      '      visaSponsorship\n' +
      '      tagline\n' +
      '      accountOwnerId\n' +
      '      updatedAt\n' +
      '      createdAt\n' +
      '      xLink {\n' +
      '        primaryLinkUrl\n' +
      '        primaryLinkLabel\n' +
      '        secondaryLinks\n' +
      '        __typename\n' +
      '      }\n' +
      '      annualRecurringRevenue {\n' +
      '        amountMicros\n' +
      '        currencyCode\n' +
      '        __typename\n' +
      '      }\n' +
      '    }\n' +
      '    position\n' +
      '    id\n' +
      '    calendarEventParticipants {\n' +
      '      edges {\n' +
      '        node {\n' +
      '          __typename\n' +
      '          handle\n' +
      '          deletedAt\n' +
      '          workspaceMemberId\n' +
      '          createdAt\n' +
      '          displayName\n' +
      '          calendarEventId\n' +
      '          updatedAt\n' +
      '          isOrganizer\n' +
      '          personId\n' +
      '          id\n' +
      '          responseStatus\n' +
      '        }\n' +
      '        __typename\n' +
      '      }\n' +
      '      __typename\n' +
      '    }\n' +
      '    deletedAt\n' +
      '    messageParticipants {\n' +
      '      edges {\n' +
      '        node {\n' +
      '          __typename\n' +
      '          displayName\n' +
      '          handle\n' +
      '          role\n' +
      '          id\n' +
      '          updatedAt\n' +
      '          deletedAt\n' +
      '          createdAt\n' +
      '          messageId\n' +
      '          workspaceMemberId\n' +
      '          personId\n' +
      '        }\n' +
      '        __typename\n' +
      '      }\n' +
      '      __typename\n' +
      '    }\n' +
      '    timelineActivities {\n' +
      '      edges {\n' +
      '        node {\n' +
      '          __typename\n' +
      '          aId\n' +
      '          personId\n' +
      '          linkedRecordCachedName\n' +
      '          workspaceMemberId\n' +
      '          name\n' +
      '          linkedObjectMetadataId\n' +
      '          happensAt\n' +
      '          rocketId\n' +
      '          companyId\n' +
      '          noteId\n' +
      '          linkedRecordId\n' +
      '          updatedAt\n' +
      '          taskId\n' +
      '          id\n' +
      '          createdAt\n' +
      '          opportunityId\n' +
      '          deletedAt\n' +
      '          properties\n' +
      '        }\n' +
      '        __typename\n' +
      '      }\n' +
      '      __typename\n' +
      '    }\n' +
      '    jobTitle\n' +
      '    workPrefereance\n' +
      '    phones {\n' +
      '      primaryPhoneNumber\n' +
      '      primaryPhoneCountryCode\n' +
      '      additionalPhones\n' +
      '      __typename\n' +
      '    }\n' +
      '    activityTargets {\n' +
      '      edges {\n' +
      '        node {\n' +
      '          __typename\n' +
      '          personId\n' +
      '          companyId\n' +
      '          rocketId\n' +
      '          deletedAt\n' +
      '          id\n' +
      '          activityId\n' +
      '          updatedAt\n' +
      '          opportunityId\n' +
      '          createdAt\n' +
      '          aId\n' +
      '        }\n' +
      '        __typename\n' +
      '      }\n' +
      '      __typename\n' +
      '    }\n' +
      '    name {\n' +
      '      firstName\n' +
      '      lastName\n' +
      '      __typename\n' +
      '    }\n' +
      '    xLink {\n' +
      '      primaryLinkUrl\n' +
      '      primaryLinkLabel\n' +
      '      secondaryLinks\n' +
      '      __typename\n' +
      '    }\n' +
      '    updatedAt\n' +
      '    createdAt\n' +
      '    city\n' +
      '    pointOfContactForOpportunities {\n' +
      '      edges {\n' +
      '        node {\n' +
      '          __typename\n' +
      '          pointOfContactId\n' +
      '          stage\n' +
      '          name\n' +
      '          id\n' +
      '          closeDate\n' +
      '          deletedAt\n' +
      '          updatedAt\n' +
      '          createdAt\n' +
      '          amount {\n' +
      '            amountMicros\n' +
      '            currencyCode\n' +
      '            __typename\n' +
      '          }\n' +
      '          companyId\n' +
      '          createdBy {\n' +
      '            source\n' +
      '            workspaceMemberId\n' +
      '            name\n' +
      '            __typename\n' +
      '          }\n' +
      '          position\n' +
      '        }\n' +
      '        __typename\n' +
      '      }\n' +
      '      __typename\n' +
      '    }\n' +
      '    avatarUrl\n' +
      '    createdBy {\n' +
      '      source\n' +
      '      workspaceMemberId\n' +
      '      name\n' +
      '      __typename\n' +
      '    }\n' +
      '  }\n' +
      '}',
    user: User {
      id: '20202020-9e3b-46d4-a556-88b9ddc2b034',
      firstName: 'Tim',
      lastName: 'Apple',
      email: 'tim@apple.dev',
      defaultAvatarUrl: null,
      emailVerified: false,
      disabled: false,
      passwordHash: '$2b$10$66d.6DuQExxnrfI9rMqOg.U1XIYpagr6Lv05uoWLYbYmtK0HDIvS6',
      canImpersonate: false,
      createdAt: 2024-10-05T10:08:47.905Z,
      updatedAt: 2024-10-05T10:08:47.905Z,
      deletedAt: null,
      defaultWorkspaceId: '20202020-1c25-4d02-bf25-6aeccf7ea419'
    }
  }
  [
    TypeError: Cannot create property 'firstName' on string 'Untitled'
        at formatResult (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/twenty-orm/utils/format-result.util.ts:136:49)
        at map (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/twenty-orm/utils/format-result.util.ts:28:7)
        at Array.map (<anonymous>)
        at formatResult (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/twenty-orm/utils/format-result.util.ts:27:17)
        at GraphqlQueryUpdateOneResolverService.resolve (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-update-one-resolver.service.ts:76:40)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at GraphqlQueryRunnerService.executeQuery (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-runner.service.ts:334:21)
        at GraphqlQueryRunnerService.updateOne (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-runner.service.ts:168:20)
        at GraphqlQueryRunnerService.descriptor.value (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/decorators/observability/log-execution-time.decorator.ts:20:22)
        at Object.updatePerson (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/update-one-resolver.factory.ts:53:18) {
      path: undefined,
      locations: undefined,
      extensions: {
        code: 'INTERNAL_SERVER_ERROR',
        response: "Cannot create property 'firstName' on string 'Untitled'"
      }
    }
  ]
```

**Comment by BOHEUS** [comment]
Related to #7449 

@Weiko please take a look at this too

**Comment by Weiko** [comment]
There is an issue the person table indeed (column "name" wrongly added and clashing with the existing composite "name" field). Has been like that for a few weeks but only visible after the recent refactoring on graphql resolvers now that we rely more heavily on metadata. This PR https://github.com/twentyhq/twenty/pull/7470 should fix that (after running the command) and will land in the next release

**Comment by Weiko** [comment]
Fixed. Running `npx nx run twenty-server:command upgrade-0.31:delete-name-column-standard-object-tables -w WORKSPACE_ID` on main should fix the issue. Will be added to migration command for 0.31.0 release.

**Comment by john-ramsey** [comment]
Getting a very similar issue here when editing any person records. Could this be a related issue?

<img width="299" alt="Image" src="https://github.com/user-attachments/assets/16ee1170-5d15-414e-8a08-f58ce95d0747" />

**Comment by john-ramsey** [comment]
Follow up has been resolved [here](https://discord.com/channels/1130383047699738754/1341714795870814228/1343894641405067294)
