### ISSUE TITLE
Account can't be deleted if file is uploaded

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7755]
**Scenario:**
1. Log in
2. Go to People tab
3. Check details of any existing record
4. Upload file
5. Go to Settings > Profile
6. Click "Delete account" button
7. Type email in input and click "Delete account" button

**Actual:** Account isn't deleted and error is thrown both in UI and logs
![image](https://github.com/user-attachments/assets/69a3ae78-dd61-4d47-900d-9ab0cddac474)

**Expected:** Account is deleted

**Comment by Bonapara** [comment]
Thanks for raising this issue @BOHEUS

**Comment by BOHEUS** [comment]
@Bonapara it's somewhat related to #7325

**Comment by ravitejamannam** [comment]
this issue no longer exists right? @Bonapara

**Comment by BOHEUS** [comment]
Still valid
```
query failed: DELETE FROM workspace_1wgvd1injqtife6y4rvfbu3h5."workspaceMember" WHERE "userId" = '20202020-9e3b-46d4-a556-88b9ddc2b034'
error: error: null value in column "authorId" of relation "attachment" violates not-null constraint
[Nest] 254250  - 03/09/2025, 9:32:25 AM   ERROR [ExceptionsHandler] null value in column "authorId" of relation "attachment" violates not-null constraint
QueryFailedError: null value in column "authorId" of relation "attachment" violates not-null constraint
    at PostgresQueryRunner.query (/home/user/Desktop/projects/twenty/src/driver/postgres/PostgresQueryRunner.ts:331:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DataSource.query (/home/user/Desktop/projects/twenty/src/data-source/DataSource.ts:538:20)
    at UserService.deleteUserFromWorkspace (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/core-modules/user/services/user.service.ts:128:5)
    at /home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/core-modules/user/services/user.service.ts:174:11
    at async Promise.all (index 0)
    at UserService.deleteUser (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/core-modules/user/services/user.service.ts:171:5)
Exception Captured
  {
    operation: { name: 'DeleteUserAccount', type: 'mutation' },
    document: 'mutation DeleteUserAccount {\n  deleteUser {\n    id\n    __typename\n  }\n}',
    user: User {
      id: '20202020-9e3b-46d4-a556-88b9ddc2b034',
      firstName: 'Tim',
      lastName: 'Apple',
      email: 'tim@apple.dev',
      defaultAvatarUrl: null,
      isEmailVerified: false,
      disabled: false,
      passwordHash: '$2b$10$66d.6DuQExxnrfI9rMqOg.U1XIYpagr6Lv05uoWLYbYmtK0HDIvS6',
      canImpersonate: true,
      canAccessFullAdminPanel: true,
      createdAt: 2025-03-02T09:30:27.377Z,
      updatedAt: 2025-03-02T09:30:27.377Z,
      deletedAt: null,
      locale: 'en'
    },
    workspace: {
      id: '20202020-1c25-4d02-bf25-6aeccf7ea419',
      displayName: 'Apple',
      createdAt: '2025-03-02T09:30:27.371Z',
      activationStatus: 'ACTIVE'
    }
  }
  [
    QueryFailedError: null value in column "authorId" of relation "attachment" violates not-null constraint
        at PostgresQueryRunner.query (/home/user/Desktop/projects/twenty/src/driver/postgres/PostgresQueryRunner.ts:331:19)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at DataSource.query (/home/user/Desktop/projects/twenty/src/data-source/DataSource.ts:538:20)
        at UserService.deleteUserFromWorkspace (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/core-modules/user/services/user.service.ts:128:5)
        at /home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/core-modules/user/services/user.service.ts:174:11
        at async Promise.all (index 0)
        at UserService.deleteUser (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/core-modules/user/services/user.service.ts:171:5) {
      path: undefined,
      locations: undefined,
      extensions: {
        code: 'INTERNAL_SERVER_ERROR',
        response: 'null value in column "authorId" of relation "attachment" violates not-null constraint'
      }
    }
  ]
query: DROP SCHEMA IF EXISTS "workspace_3ixj3i1a5avy16ptijtb3lae3" CASCADE
Exception Captured
  undefined
  [
    Error: [FileWorkspaceFolderDeletionJob] Cannot delete workspace folder - 3b8e6458-5fc1-4e63-8563-008ccddaa6db
        at FileWorkspaceFolderDeletionJob.handle (/home/user/Desktop/projects/twenty/packages/twenty-server/dist/src/engine/core-modules/file/jobs/file-workspace-folder-deletion.job.js:30:19)
        at async MessageQueueExplorer.invokeProcessMethods (/home/user/Desktop/projects/twenty/packages/twenty-server/dist/src/engine/core-modules/message-queue/message-queue.explorer.js:111:17)
        at async MessageQueueExplorer.handleProcessor (/home/user/Desktop/projects/twenty/packages/twenty-server/dist/src/engine/core-modules/message-queue/message-queue.explorer.js:105:13)
        at async /home/user/Desktop/projects/twenty/packages/twenty-server/dist/src/engine/core-modules/message-queue/message-queue.explorer.js:79:17
        at async Worker.processFn (/home/user/Desktop/projects/twenty/packages/twenty-server/dist/src/engine/core-modules/message-queue/drivers/bullmq.driver.js:41:13)
        at async /home/user/Desktop/projects/twenty/node_modules/bullmq/dist/cjs/classes/worker.js:520:32
        at async Worker.retryIfFailed (/home/user/Desktop/projects/twenty/node_modules/bullmq/dist/cjs/classes/worker.js:747:24)
  ]
```

**Comment by FelixMalfait** [comment]
Converting to high since it still hasn't been tackled

**Comment by charlesBochet** [comment]
Fixed in 0.44
