### ISSUE TITLE
TAG=v0.31.2 - All rest calls 500

### ISSUE THREAD

**Issue by rosscdh** [twentyhq/twenty#7808]
## Bug Description

All rest calls to any endpoint result in a 500 error (which does not show in logs nor in stdout)

**Example:** 
```
 curl -vv --request GET \
  --url http://0.0.0.0:3010/rest/timelineActivities \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXV....aqrERiUA'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 0.0.0.0:3010...
* Connected to 0.0.0.0 (127.0.0.1) port 3010 (#0)
> GET /rest/timelineActivities HTTP/1.1
> Host: 0.0.0.0:3010
> User-Agent: curl/7.86.0
> Accept: application/json
> Authorization: Bearer eyJhbGciOiJ......RiUA
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET,HEAD,PUT,PATCH,POST,DELETE
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
< Content-Type: application/json; charset=utf-8
< Date: Thu, 17 Oct 2024 21:02:53 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Content-Length: 0
<
* Connection #0 to host 0.0.0.0 left intact
```

The server is up and running as per being able to query the openapispec

```
 curl -vv --request GET \
  --url http://0.0.0.0:3010/open-api/core \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR....-aqrERiUA'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 0.0.0.0:3010...
* Connected to 0.0.0.0 (127.0.0.1) port 3010 (#0)
> GET /open-api/core HTTP/1.1
> Host: 0.0.0.0:3010
> User-Agent: curl/7.86.0
> Accept: application/json
> Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR....FFNHT0bM-aqrERiUA
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Content-Type: application/json; charset=utf-8
< Content-Length: 388233
< ETag: W/"5ec89-6YxSUxmfDcbP9eTDSMUrCEHjDnw"
< Date: Thu, 17 Oct 2024 21:06:27 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
{"openapi":"3.0.3","info":{"title":"Twenty Api","description":"This is a **Twenty REST/API**
```

## Expected behavior

A set of endpoints that does not error out?

**Comment by rosscdh** [comment]
This appears to be the issue, however the token i am using is valid... 

```
twenty-server-1                | Exception Captured
twenty-server-1                |   {
twenty-server-1                |     operation: { name: 'GetCurrentUser', type: 'query' },
twenty-server-1                |     document: 'query GetCurrentUser {\n' +
twenty-server-1                |       '  currentUser {\n' +
twenty-server-1                |       '    ...UserQueryFragment\n' +
twenty-server-1                |       '    __typename\n' +
twenty-server-1                |       '  }\n' +
twenty-server-1                |       '}\n' +
twenty-server-1                |       '\n' +
twenty-server-1                |       'fragment UserQueryFragment on User {\n' +
twenty-server-1                |       '  id\n' +
twenty-server-1                |       '  firstName\n' +
twenty-server-1                |       '  lastName\n' +
twenty-server-1                |       '  email\n' +
twenty-server-1                |       '  canImpersonate\n' +
twenty-server-1                |       '  supportUserHash\n' +
twenty-server-1                |       '  onboardingStatus\n' +
twenty-server-1                |       '  workspaceMember {\n' +
twenty-server-1                |       '    ...WorkspaceMemberQueryFragment\n' +
twenty-server-1                |       '    __typename\n' +
twenty-server-1                |       '  }\n' +
twenty-server-1                |       '  workspaceMembers {\n' +
twenty-server-1                |       '    ...WorkspaceMemberQueryFragment\n' +
twenty-server-1                |       '    __typename\n' +
twenty-server-1                |       '  }\n' +
twenty-server-1                |       '  defaultWorkspace {\n' +
twenty-server-1                |       '    id\n' +
twenty-server-1                |       '    displayName\n' +
twenty-server-1                |       '    logo\n' +
twenty-server-1                |       '    domainName\n' +
twenty-server-1                |       '    inviteHash\n' +
twenty-server-1                |       '    allowImpersonation\n' +
twenty-server-1                |       '    activationStatus\n' +
twenty-server-1                |       '    featureFlags {\n' +
twenty-server-1                |       '      id\n' +
twenty-server-1                |       '      key\n' +
twenty-server-1                |       '      value\n' +
twenty-server-1                |       '      workspaceId\n' +
twenty-server-1                |       '      __typename\n' +
twenty-server-1                |       '    }\n' +
twenty-server-1                |       '    metadataVersion\n' +
twenty-server-1                |       '    currentBillingSubscription {\n' +
twenty-server-1                |       '      id\n' +
twenty-server-1                |       '      status\n' +
twenty-server-1                |       '      interval\n' +
twenty-server-1                |       '      __typename\n' +
twenty-server-1                |       '    }\n' +
twenty-server-1                |       '    workspaceMembersCount\n' +
twenty-server-1                |       '    __typename\n' +
twenty-server-1                |       '  }\n' +
twenty-server-1                |       '  workspaces {\n' +
twenty-server-1                |       '    workspace {\n' +
twenty-server-1                |       '      id\n' +
twenty-server-1                |       '      logo\n' +
twenty-server-1                |       '      displayName\n' +
twenty-server-1                |       '      domainName\n' +
twenty-server-1                |       '      __typename\n' +
twenty-server-1                |       '    }\n' +
twenty-server-1                |       '    __typename\n' +
twenty-server-1                |       '  }\n' +
twenty-server-1                |       '  userVars\n' +
twenty-server-1                |       '  __typename\n' +
twenty-server-1                |       '}\n' +
twenty-server-1                |       '\n' +
twenty-server-1                |       'fragment WorkspaceMemberQueryFragment on WorkspaceMember {\n' +
twenty-server-1                |       '  id\n' +
twenty-server-1                |       '  name {\n' +
twenty-server-1                |       '    firstName\n' +
twenty-server-1                |       '    lastName\n' +
twenty-server-1                |       '    __typename\n' +
twenty-server-1                |       '  }\n' +
twenty-server-1                |       '  colorScheme\n' +
twenty-server-1                |       '  avatarUrl\n' +
twenty-server-1                |       '  locale\n' +
twenty-server-1                |       '  timeZone\n' +
twenty-server-1                |       '  dateFormat\n' +
twenty-server-1                |       '  timeFormat\n' +
twenty-server-1                |       '  __typename\n' +
twenty-server-1                |       '}',
twenty-server-1                |     user: undefined
twenty-server-1                |   }
twenty-server-1                |   [
twenty-server-1                |     ForbiddenException: Forbidden resource
twenty-server-1                |         at canActivateFn (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:157:23)
twenty-server-1                |         at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
twenty-server-1                |         at async target (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:73:31)
twenty-server-1                |         at async Object.currentUser (/app/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
twenty-server-1                |         at async field.resolve (/app/node_modules/@envelop/on-resolve/cjs/index.js:36:42)
twenty-server-1                |         at async /app/node_modules/@graphql-tools/executor/cjs/execution/promiseForObject.js:18:35
twenty-server-1                |         at async Promise.all (index 0) {
twenty-server-1                |       path: undefined,
twenty-server-1                |       locations: undefined,
twenty-server-1                |       extensions: { code: 'INTERNAL_SERVER_ERROR', response: 'Forbidden resource' }
twenty-server-1                |     }
twenty-server-1                |   ]
twenty-server-1                | metadata query time: 3.6480299830436707 ms
```

**Comment by rosscdh** [comment]
whats also weird is if i give a wrong token it will reject 403 forbidden.. so its getting to auth layer.. but something internal throws its hands up

```
➭ curl -vv --request GET \
  --url http://0.0.0.0:3010/rest/people \
  --header 'Accept: application/json' \
  --header "Authorization: Bearer $TWENTY_TOKEN"
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 0.0.0.0:3010...
* Connected to 0.0.0.0 (127.0.0.1) port 3010 (#0)
> GET /rest/people HTTP/1.1
> Host: 0.0.0.0:3010
> User-Agent: curl/7.86.0
> Accept: application/json
> Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5...AFyvl31p1gmTB0_0uzpvslv__0sNbg_Dno
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< X-Powered-By: Express
```

**Comment by charlesBochet** [comment]
@rosscdh I think our controllers are not logging errors properly, I suspect that there is something wrong with your server setup.
Is the front running properly (as it's leveraging the GraphqlAPI direclty, we might have more logs)?

**Comment by rosscdh** [comment]
Hmm it's stock standard docker compose curled from the docs?

Nothing special going on

**Comment by martmull** [comment]
@rosscdh I can't reproduce on main:
```bash
curl -vv --request GET \
  --url http://0.0.0.0:3000/rest/timelineActivities \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer <obfuscated>...8Y6E'
```
return
```json
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 0.0.0.0:3000...
* Connected to 0.0.0.0 (127.0.0.1) port 3000
> GET /rest/timelineActivities HTTP/1.1
> Host: 0.0.0.0:3000
> User-Agent: curl/8.4.0
> Accept: application/json
> Authorization: Bearer <obfuscated>...8Y6E
>
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Content-Type: application/json; charset=utf-8
< Content-Length: 10736
< ETag: W/"29f0-oDNWvoeX6n4zWgWZJ7Tq5Bon01o"
< Date: Fri, 18 Oct 2024 08:35:26 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
{"data":{"timelineActivities":[{"id":"21d6aea3-cfcd-4df5-8841-54bef70f223c","happensAt":"2024-10-18T08:11:55.403Z","name":"company.created","properties":{"after":{"id":"dd45e98c-4826-45c3-9554-524e0417dbb3","name":"tata","xLink":{"primaryLinkUrl":"","secondaryLinks":null,"primaryLinkLabel":""},"address":...,"updatedAt":"2024-10-17T10:10:57.063Z","deletedAt":null,"name":{"firstName":"Tim","lastName":"Apple"}}}]},"pageInfo":{"hasNextPage":false,"startCursor":"eyJpZCI6IjIxZDZhZWEzLWNmY2QtNGRmNS04ODQxLTU0YmVmNzBmMjIzYyJ9","endCursor":"eyJpZCI6ImY3M2IyYzdlLTUwNWMtNDY4YS1hZDcwLTQxZTQxZjUxMTY1MSJ9"},"totalCount":5}
```
And 
```bash
curl -vv --request GET \
  --url http://0.0.0.0:3000/rest/timelineActivities \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer <OFFUSCATED>...8Y6E-<WRONG_BEARER>'
```
return
```json
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 0.0.0.0:3000...
* Connected to 0.0.0.0 (127.0.0.1) port 3000
> GET /rest/timelineActivities HTTP/1.1
> Host: 0.0.0.0:3000
> User-Agent: curl/8.4.0
> Accept: application/json
> Authorization: Bearer <OFFUSCATED>...8Y6E-<WRONG_BEARER>
>
< HTTP/1.1 403 Forbidden
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET,HEAD,PUT,PATCH,POST,DELETE
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
< Content-Type: application/json; charset=utf-8
< Content-Length: 69
< ETag: W/"45-T7Txzr/IRLfQ4TEPfbVWLpgje4Q"
< Date: Fri, 18 Oct 2024 08:37:19 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host 0.0.0.0 left intact
{"statusCode":403,"message":"Forbidden resource","error":"Forbidden"}
```

**Comment by rosscdh** [comment]
@Bonapara no this was not completed mate... sorry

I have found the issue however

docker compose

ports:
3010:3000 <---- it seems the system uses the internal running port as part of the token generation

I changed to run on 3010 via the env var and the internal port mapping and voila

```
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Content-Type: application/json; charset=utf-8
< Content-Length: 2299
< ETag: W/"8fb-cGcSEvhkxKBG0V5scMggwbnY/Us"
< Date: Fri, 18 Oct 2024 09:13:20 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host 0.0.0.0 left intact
{"data":{"people":[{"id":"44c34c5b-b5bc-46aa-9b30-4128f93a48c0","jobTitle":"","city":"","avatarUrl":"","position":0,"createdAt":"2024-10-18T07:12:46.136Z","updatedAt":"2024-10-18T07:12:46.136Z","deletedAt":null,"companyId":null,"company":null,"name":{"firstName":"Scott Jack","lastName":""},"emails":{"primaryEmail":"","additionalEmails":null},"linkedinLink":{"primaryLinkLabel":"","primaryLinkUrl":"","secondaryLinks":null},"xLink":{"primaryLinkLabel":"","primaryLinkUrl":"","secondaryLinks":null},"phones":{"primaryPhoneNumber":"
```
