### ISSUE TITLE
Environment Variable failing string check

### ISSUE THREAD

**Issue by technicalnoodles** [twentyhq/twenty#8265]
## Bug Description

When trying to run the self-hosted docker compose for the lastest version, I get errors that the multiple tokens are failing a string check.

```
twenty@twenty:~/v32-twenty$ sudo docker compose up
WARN[0000] The "STORAGE_S3_REGION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "STORAGE_S3_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "STORAGE_S3_ENDPOINT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "STORAGE_S3_REGION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "STORAGE_S3_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "STORAGE_S3_ENDPOINT" variable is not set. Defaulting to a blank string. 
WARN[0000] /home/homelab/v32-twenty/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 6/4
 ✔ Network v32-twenty_default                   Created                                                                                                                                             0.0s 
 ✔ Container v32-twenty-change-vol-ownership-1  Created                                                                                                                                             0.1s 
 ✔ Container v32-twenty-db-1                    Created                                                                                                                                             0.1s 
 ✔ Container v32-twenty-redis-1                 Created                                                                                                                                             0.1s 
 ✔ Container v32-twenty-server-1                Created                                                                                                                                             0.0s 
 ✔ Container v32-twenty-worker-1                Created                                                                                                                                             0.0s 
Attaching to change-vol-ownership-1, db-1, redis-1, server-1, worker-1
redis-1                 | 1:C 31 Oct 2024 19:14:52.308 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis-1                 | 1:C 31 Oct 2024 19:14:52.308 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-1                 | 1:C 31 Oct 2024 19:14:52.308 * Redis version=7.4.1, bits=64, commit=00000000, modified=0, pid=1, just started
redis-1                 | 1:C 31 Oct 2024 19:14:52.308 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis-1                 | 1:M 31 Oct 2024 19:14:52.309 * monotonic clock: POSIX clock_gettime
redis-1                 | 1:M 31 Oct 2024 19:14:52.309 * Running mode=standalone, port=6379.
redis-1                 | 1:M 31 Oct 2024 19:14:52.310 * Server initialized
redis-1                 | 1:M 31 Oct 2024 19:14:52.310 * Ready to accept connections tcp
db-1                    | postgresql 19:14:52.31 INFO  ==> 
db-1                    | postgresql 19:14:52.31 INFO  ==> Welcome to the Bitnami postgresql container
db-1                    | postgresql 19:14:52.31 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
db-1                    | postgresql 19:14:52.31 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
db-1                    | postgresql 19:14:52.31 INFO  ==> 
db-1                    | postgresql 19:14:52.32 INFO  ==> ** Starting PostgreSQL setup **
change-vol-ownership-1 exited with code 0
db-1                    | postgresql 19:14:52.33 INFO  ==> Validating settings in POSTGRESQL_* env vars..
db-1                    | postgresql 19:14:52.33 INFO  ==> Loading custom pre-init scripts...
db-1                    | postgresql 19:14:52.33 INFO  ==> Initializing PostgreSQL database...
db-1                    | postgresql 19:14:52.34 INFO  ==> pg_hba.conf file not detected. Generating it...
db-1                    | postgresql 19:14:52.34 INFO  ==> Generating local authentication configuration
db-1                    | postgresql 19:14:52.35 INFO  ==> Deploying PostgreSQL with persisted data...
db-1                    | postgresql 19:14:52.35 INFO  ==> Configuring replication parameters
db-1                    | postgresql 19:14:52.36 INFO  ==> Configuring fsync
db-1                    | postgresql 19:14:52.37 INFO  ==> Configuring synchronous_replication
db-1                    | postgresql 19:14:52.38 INFO  ==> Loading custom scripts...
db-1                    | postgresql 19:14:52.38 INFO  ==> Enabling remote connections
db-1                    | postgresql 19:14:52.38 INFO  ==> ** PostgreSQL setup finished! **
db-1                    | 
db-1                    | postgresql 19:14:52.39 INFO  ==> ** Starting PostgreSQL **
db-1                    | 2024-10-31 19:14:52.407 GMT [1] LOG:  pgaudit extension initialized
db-1                    | 2024-10-31 19:14:52.413 GMT [1] LOG:  starting PostgreSQL 15.5 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db-1                    | 2024-10-31 19:14:52.414 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1                    | 2024-10-31 19:14:52.414 GMT [1] LOG:  listening on IPv6 address "::", port 5432
db-1                    | 2024-10-31 19:14:52.419 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
db-1                    | 2024-10-31 19:14:52.425 GMT [85] LOG:  database system was shut down at 2024-10-31 19:14:44 GMT
db-1                    | 2024-10-31 19:14:52.430 GMT [1] LOG:  database system is ready to accept connections
server-1                | /app/packages/twenty-server/dist/src/utils/assert.js:27
server-1                |         throw new Error(message);
server-1                |         ^
server-1                | 
server-1                | Error: An instance of EnvironmentVariables has failed the validation:
server-1                |  - property ACCESS_TOKEN_SECRET has failed the following constraints: isString 
server-1                | ,An instance of EnvironmentVariables has failed the validation:
server-1                |  - property REFRESH_TOKEN_SECRET has failed the following constraints: isString 
server-1                | 
server-1                |     at assert (/app/packages/twenty-server/dist/src/utils/assert.js:27:15)
server-1                |     at Object.validate (/app/packages/twenty-server/dist/src/engine/core-modules/environment/environment-variables.js:521:24)
server-1                |     at ConfigModule.forRoot (/app/node_modules/@nestjs/config/dist/config.module.js:67:45)
server-1                |     at Object.<anonymous> (/app/packages/twenty-server/dist/src/engine/core-modules/environment/environment.module.js:28:34)
server-1                |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
server-1                |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
server-1                |     at Module.load (node:internal/modules/cjs/loader:1119:32)
server-1                |     at Module._load (node:internal/modules/cjs/loader:960:12)
server-1                |     at Module.require (node:internal/modules/cjs/loader:1143:19)
server-1                |     at require (node:internal/modules/cjs/helpers:121:18)
server-1                | 
server-1                | Node.js v18.17.1
server-1 exited with code 1
server-1                | /app/packages/twenty-server/dist/src/utils/assert.js:27
server-1                |         throw new Error(message);
server-1                |         ^
server-1                | 
server-1                | Error: An instance of EnvironmentVariables has failed the validation:
server-1                |  - property ACCESS_TOKEN_SECRET has failed the following constraints: isString 
server-1                | ,An instance of EnvironmentVariables has failed the validation:
server-1                |  - property REFRESH_TOKEN_SECRET has failed the following constraints: isString 
server-1                | 
server-1                |     at assert (/app/packages/twenty-server/dist/src/utils/assert.js:27:15)
server-1                |     at Object.validate (/app/packages/twenty-server/dist/src/engine/core-modules/environment/environment-variables.js:521:24)
server-1                |     at ConfigModule.forRoot (/app/node_modules/@nestjs/config/dist/config.module.js:67:45)
server-1                |     at Object.<anonymous> (/app/packages/twenty-server/dist/src/engine/core-modules/environment/environment.module.js:28:34)
server-1                |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
server-1                |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
server-1                |     at Module.load (node:internal/modules/cjs/loader:1119:32)
server-1                |     at Module._load (node:internal/modules/cjs/loader:960:12)
server-1                |     at Module.require (node:internal/modules/cjs/loader:1143:19)
server-1                |     at require (node:internal/modules/cjs/helpers:121:18)
server-1                | 
server-1                | Node.js v18.17.1
dependency failed to start: container v32-twenty-server-1 is unhealthy
[screenshot]
```

## Expected behavior

I'm expecting to have any environment variable issues

## Technical inputs
Here is my .env file.  After editing this, I run docker compose up -d
```
TAG=latest

POSTGRES_ADMIN_PASSWORD=password

PG_DATABASE_HOST=db:5432
REDIS_URL=redis://redis:6379

SERVER_URL=http://localhost:3000

# Use openssl rand -base64 32 for each secret
APP_SECRET=secret

SIGN_IN_PREFILLED=true

STORAGE_TYPE=local

# STORAGE_S3_REGION=eu-west3
# STORAGE_S3_NAME=my-bucket
# STORAGE_S3_ENDPOINT=
```

**Comment by ketanMehtaa** [comment]
Try adding these in packages/twenty-server/.env

ACCESS_TOKEN_SECRET=replace_me_with_a_random_string_access
LOGIN_TOKEN_SECRET=replace_me_with_a_random_string_login
REFRESH_TOKEN_SECRET=replace_me_with_a_random_string_refresh
FILE_TOKEN_SECRET=replace_me_with_a_random_string_refresh
SIGN_IN_PREFILLED=true

**Comment by technicalnoodles** [comment]
I get that same error with those in the .env file

```
twenty@twenty:~/v32-twenty$ sudo docker compose up
WARN[0000] The "STORAGE_S3_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "STORAGE_S3_REGION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "STORAGE_S3_ENDPOINT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "STORAGE_S3_REGION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "STORAGE_S3_ENDPOINT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "STORAGE_S3_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] /home/homelab/v32-twenty/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 6/4
 ✔ Network v32-twenty_default                   Created                                                                                                                                             0.0s 
 ✔ Container v32-twenty-change-vol-ownership-1  Created                                                                                                                                             0.1s 
 ✔ Container v32-twenty-db-1                    Created                                                                                                                                             0.1s 
 ✔ Container v32-twenty-redis-1                 Created                                                                                                                                             0.1s 
 ✔ Container v32-twenty-server-1                Created                                                                                                                                             0.0s 
 ✔ Container v32-twenty-worker-1                Created                                                                                                                                             0.0s 
Attaching to change-vol-ownership-1, db-1, redis-1, server-1, worker-1
db-1                    | postgresql 20:53:58.93 INFO  ==> 
db-1                    | postgresql 20:53:58.93 INFO  ==> Welcome to the Bitnami postgresql container
db-1                    | postgresql 20:53:58.93 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
db-1                    | postgresql 20:53:58.93 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
db-1                    | postgresql 20:53:58.93 INFO  ==> 
db-1                    | postgresql 20:53:58.94 INFO  ==> ** Starting PostgreSQL setup **
redis-1                 | 1:C 31 Oct 2024 20:53:58.962 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
db-1                    | postgresql 20:53:58.96 INFO  ==> Validating settings in POSTGRESQL_* env vars..
redis-1                 | 1:C 31 Oct 2024 20:53:58.963 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-1                 | 1:C 31 Oct 2024 20:53:58.964 * Redis version=7.4.1, bits=64, commit=00000000, modified=0, pid=1, just started
redis-1                 | 1:C 31 Oct 2024 20:53:58.964 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis-1                 | 1:M 31 Oct 2024 20:53:58.964 * monotonic clock: POSIX clock_gettime
redis-1                 | 1:M 31 Oct 2024 20:53:58.965 * Running mode=standalone, port=6379.
redis-1                 | 1:M 31 Oct 2024 20:53:58.966 * Server initialized
redis-1                 | 1:M 31 Oct 2024 20:53:58.966 * Ready to accept connections tcp
db-1                    | postgresql 20:53:58.96 INFO  ==> Loading custom pre-init scripts...
db-1                    | postgresql 20:53:58.97 INFO  ==> Initializing PostgreSQL database...
db-1                    | postgresql 20:53:58.97 INFO  ==> pg_hba.conf file not detected. Generating it...
db-1                    | postgresql 20:53:58.98 INFO  ==> Generating local authentication configuration
db-1                    | postgresql 20:53:58.98 INFO  ==> Deploying PostgreSQL with persisted data...
db-1                    | postgresql 20:53:58.99 INFO  ==> Configuring replication parameters
db-1                    | postgresql 20:53:59.01 INFO  ==> Configuring fsync
db-1                    | postgresql 20:53:59.01 INFO  ==> Configuring synchronous_replication
db-1                    | postgresql 20:53:59.02 INFO  ==> Loading custom scripts...
db-1                    | postgresql 20:53:59.02 INFO  ==> Enabling remote connections
db-1                    | 
db-1                    | postgresql 20:53:59.03 INFO  ==> ** PostgreSQL setup finished! **
change-vol-ownership-1 exited with code 0
db-1                    | postgresql 20:53:59.04 INFO  ==> ** Starting PostgreSQL **
db-1                    | 2024-10-31 20:53:59.055 GMT [1] LOG:  pgaudit extension initialized
db-1                    | 2024-10-31 20:53:59.061 GMT [1] LOG:  starting PostgreSQL 15.5 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db-1                    | 2024-10-31 20:53:59.062 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1                    | 2024-10-31 20:53:59.062 GMT [1] LOG:  listening on IPv6 address "::", port 5432
db-1                    | 2024-10-31 20:53:59.067 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
db-1                    | 2024-10-31 20:53:59.074 GMT [85] LOG:  database system was shut down at 2024-10-31 20:53:51 GMT
db-1                    | 2024-10-31 20:53:59.079 GMT [1] LOG:  database system is ready to accept connections
server-1                | /app/packages/twenty-server/dist/src/utils/assert.js:27
server-1                |         throw new Error(message);
server-1                |         ^
server-1                | 
server-1                | Error: An instance of EnvironmentVariables has failed the validation:
server-1                |  - property ACCESS_TOKEN_SECRET has failed the following constraints: isString 
server-1                | ,An instance of EnvironmentVariables has failed the validation:
server-1                |  - property REFRESH_TOKEN_SECRET has failed the following constraints: isString 
server-1                | 
server-1                |     at assert (/app/packages/twenty-server/dist/src/utils/assert.js:27:15)
server-1                |     at Object.validate (/app/packages/twenty-server/dist/src/engine/core-modules/environment/environment-variables.js:521:24)
server-1                |     at ConfigModule.forRoot (/app/node_modules/@nestjs/config/dist/config.module.js:67:45)
server-1                |     at Object.<anonymous> (/app/packages/twenty-server/dist/src/engine/core-modules/environment/environment.module.js:28:34)
server-1                |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
server-1                |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
server-1                |     at Module.load (node:internal/modules/cjs/loader:1119:32)
server-1                |     at Module._load (node:internal/modules/cjs/loader:960:12)
server-1                |     at Module.require (node:internal/modules/cjs/loader:1143:19)
server-1                |     at require (node:internal/modules/cjs/helpers:121:18)
server-1                | 
server-1                | Node.js v18.17.1
server-1 exited with code 1
server-1                | /app/packages/twenty-server/dist/src/utils/assert.js:27
server-1                |         throw new Error(message);
server-1                |         ^
server-1                | 
server-1                | Error: An instance of EnvironmentVariables has failed the validation:
server-1                |  - property ACCESS_TOKEN_SECRET has failed the following constraints: isString 
server-1                | ,An instance of EnvironmentVariables has failed the validation:
server-1                |  - property REFRESH_TOKEN_SECRET has failed the following constraints: isString 
server-1                | 
server-1                |     at assert (/app/packages/twenty-server/dist/src/utils/assert.js:27:15)
server-1                |     at Object.validate (/app/packages/twenty-server/dist/src/engine/core-modules/environment/environment-variables.js:521:24)
server-1                |     at ConfigModule.forRoot (/app/node_modules/@nestjs/config/dist/config.module.js:67:45)
server-1                |     at Object.<anonymous> (/app/packages/twenty-server/dist/src/engine/core-modules/environment/environment.module.js:28:34)
server-1                |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
server-1                |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
server-1                |     at Module.load (node:internal/modules/cjs/loader:1119:32)
server-1                |     at Module._load (node:internal/modules/cjs/loader:960:12)
server-1                |     at Module.require (node:internal/modules/cjs/loader:1143:19)
server-1                |     at require (node:internal/modules/cjs/helpers:121:18)
server-1                | 
server-1                | Node.js v18.17.1
dependency failed to start: container v32-twenty-server-1 is unhealthy
```

**Comment by splatrac** [comment]
i confirm the same error in docker using .env file when trying anything as token secrets

**Comment by Hitarthsheth07** [comment]
Pull the latest code. They've changed the env file. Then copy .env.example to .env. 

Let me know if this works

**Comment by FelixMalfait** [comment]
Mmh strange, looks like it's asking for you to setup S3 but if `STORAGE_TYPE=local` it shouldn't, unless you have specifically set STORAGE_TYPE to S3 (the default value is local). Are you sure it isn't set to S3 somewhere? Thanks!

**Comment by technicalnoodles** [comment]
@Hitarthsheth07 I'm using the latest env file. I've been pulling the env file from the most recent code repo and it says it hasn't been updated in 2 days.

@FelixMalfait The S3 storage type isnt an issue.  The warnings are the same from version 24 all the way up to 31. And now the latest as well. S3 configs shouldnt be causing any issues here. 

From what I am seeing, there is an issue with the env variables not being pulled properly. Or the check for the variables isn't right. I'm not sure which.  

```
server-1                | /app/packages/twenty-server/dist/src/utils/assert.js:27
server-1                |         throw new Error(message);
server-1                |         ^
server-1                | 
server-1                | Error: An instance of EnvironmentVariables has failed the validation:
server-1                |  - property ACCESS_TOKEN_SECRET has failed the following constraints: isString 
server-1                | ,An instance of EnvironmentVariables has failed the validation:
server-1                |  - property REFRESH_TOKEN_SECRET has failed the following constraints: isString 
server-1                | 
```

We shouldnt need to pass the these secrets anymore and when adding them to the env file, the application still fails to start because it is failing the token type check.

**Comment by technicalnoodles** [comment]
I was able to fix this issue by adding the secrets back to the docker compose file for the server and worker.  I'm going to leave this open as we shouldn't need to do that anymore with the change to APP_SECRET

**Comment by FelixMalfait** [comment]
Yes read too quickly sorry!
We need to publish the new docker image, there's a discrepancy because of this. The docker image will be updated this week, and there won't be the issue anymore.

**Comment by jgoyvaerts** [comment]
@FelixMalfait Any idea when this will be done? It's a bit misleading to close this issue as the issue is still present in the current docker image, I just ran into the same problem

**Comment by tcmonster** [comment]
same issue here. pls tell me when it'll be fixed

**Comment by FelixMalfait** [comment]
The new docker image was just published (with the right environment variables) but unfortunately we discovered it has an issue if you use API keys, so I'd recommend waiting for later today to download the new one we'll publish

**Comment by alvares** [comment]
some question here. Have you already published the fix?

**Comment by FelixMalfait** [comment]
Yes it was published on Nov 6.

Note PG_DATABASE_HOST should be `db` and not `db:5432`

**Comment by ciarans** [comment]
Still an active problem - keeps crashing the worker
