### ISSUE TITLE
Error in devtools while checking fields of object

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8298]
**Scenario:**
1. Log in
2. Go to Settings > Data model > any object

**Actual:** There's error in devtools 
![image](https://github.com/user-attachments/assets/0a13a71f-803d-403c-9ea4-de4311cc16c1)

**Expected:** There should be no error in devtools

**Error:**
```
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. Error Component Stack
    at a (<anonymous>)
    at LinkWithRef (react-router-dom.js?v=6cd587e7:5264:5)
    at chunk-CXFQHRW6.js?v=6cd587e7:1278:45
    at SettingsObjectFieldDataType (SettingsObjectFieldDataType.tsx:54:3)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=6cd587e7:1278:45
    at a (<anonymous>)
    at LinkWithRef (react-router-dom.js?v=6cd587e7:5264:5)
    at chunk-CXFQHRW6.js?v=6cd587e7:1278:45
    at TableRow (TableRow.tsx:50:3)
    at chunk-CXFQHRW6.js?v=6cd587e7:1278:45
    at SettingsObjectFieldItemTableRow (SettingsObjectFieldItemTableRow.tsx:65:3)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=6cd587e7:1278:45
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=6cd587e7:1278:45
    at TableSection (TableSection.tsx:43:3)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=6cd587e7:1278:45
    at SettingsObjectFieldTable (SettingsObjectFieldTable.tsx:91:3)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=6cd587e7:1278:45
    at Section (Section.tsx:34:3)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=6cd587e7:1278:45
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=6cd587e7:1278:45
    at ScrollWrapper (ScrollWrapper.tsx:35:3)
    at SettingsPageContainer (SettingsPageContainer.tsx:27:3)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=6cd587e7:1278:45
    at PagePanel (PagePanel.tsx:19:29)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=6cd587e7:1278:45
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=6cd587e7:1278:45
    at PageBody (PageBody.tsx:43:28)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=6cd587e7:1278:45
    at SubMenuTopBarContainer (SubMenuTopBarContainer.tsx:34:3)
    at SettingsObjectDetailPageContent (SettingsObjectDetailPageContent.tsx:28:3)
    at SettingsObjectDetailPage (SettingsObjectDetailPage.tsx:10:20)
    at RenderedRoute (react-router-dom.js?v=6cd587e7:4035:5)
    at Routes (react-router-dom.js?v=6cd587e7:4474:5)
    at Suspense (<anonymous>)
    at SettingsRoutes (SettingsRoutes.tsx:259:3)
    at RenderedRoute (react-router-dom.js?v=6cd587e7:4035:5)
    at Outlet (react-router-dom.js?v=6cd587e7:4410:26)
    at ErrorBoundary (react-error-boundary.js?v=6cd587e7:18:5)
    at AppErrorBoundary (AppErrorBoundary.tsx:7:36)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=6cd587e7:1278:45
    at div (<anonymous>)
    at MotionComponent (framer-motion.js?v=6cd587e7:277:40)
    at chunk-CXFQHRW6.js?v=6cd587e7:1278:45
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=6cd587e7:1278:45
    at DefaultLayout (DefaultLayout.tsx:62:20)
    at RenderedRoute (react-router-dom.js?v=6cd587e7:4035:5)
    at Outlet (react-router-dom.js?v=6cd587e7:4410:26)
    at DialogManager (DialogManager.tsx:7:33)
    at DialogManagerScope (DialogManagerScope.tsx:11:3)
    at SnackBarProvider (SnackBarProvider.tsx:27:36)
    at ThemeContextProvider (ThemeContextProvider.tsx:14:3)
    at ThemeProvider2 (chunk-CXFQHRW6.js?v=6cd587e7:1308:22)
    at AppThemeProvider (AppThemeProvider.tsx:12:36)
    at PrefetchDataProvider (PrefetchDataProvider.tsx:5:40)
    at RelationPickerScope (RelationPickerScope.tsx:11:3)
    at PreComputedChipGeneratorsProvider (PreComputedChipGeneratorsProvider.tsx:9:3)
    at ObjectMetadataItemsProvider (ObjectMetadataItemsProvider.tsx:11:3)
    at ApolloMetadataClientProvider (ApolloMetadataClientProvider.tsx:7:3)
    at AuthProvider (AuthProvider.tsx:7:32)
    at UserProvider (UserProvider.tsx:11:32)
    at ChromeExtensionSidecarProvider (ChromeExtensionSidecarProvider.tsx:25:8)
    at ClientConfigProvider (ClientConfigProvider.tsx:6:3)
    at ApolloProvider (@apollo_client.js?v=6cd587e7:161:19)
    at ApolloProvider (ApolloProvider.tsx:5:34)
    at AppRouterProviders (AppRouterProviders.tsx:26:24)
    at RenderedRoute (react-router-dom.js?v=6cd587e7:4035:5)
    at RenderErrorBoundary (react-router-dom.js?v=6cd587e7:3995:5)
    at DataRoutes (react-router-dom.js?v=6cd587e7:5154:5)
    at Router (react-router-dom.js?v=6cd587e7:4417:15)
    at RouterProvider (react-router-dom.js?v=6cd587e7:4969:5)
    at AppRouter (AppRouter.tsx:8:19)
    at r2 (react-helmet-async.js?v=6cd587e7:387:21)
    at ExceptionHandlerProvider (ExceptionHandlerProvider.tsx:4:3)
    at IconsProvider (IconsProvider.tsx:10:33)
    at SnackBarProviderScope (SnackBarProviderScope.tsx:11:3)
    at CaptchaProvider (CaptchaProvider.tsx:5:35)
    at ErrorBoundary (react-error-boundary.js?v=6cd587e7:18:5)
    at AppErrorBoundary (AppErrorBoundary.tsx:7:36)
    at RecoilRoot_INTERNAL (recoil.js?v=6cd587e7:2795:3)
    at RecoilRoot (recoil.js?v=6cd587e7:2913:5)
    at App (<anonymous>)
```

**Comment by khuddite** [comment]
I am working on the issue
