### ISSUE TITLE
validateDOMNesting(...): <a> cannot appear as a descendant of <a>

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#8530]
Saw this error when accessing an object's Settings:

![Image](https://github.com/user-attachments/assets/7f43d016-1b5a-4809-938b-3d3fe3f7087c)

Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. Error Component Stack
    at a (<anonymous>)
    at LinkWithRef (react-router-dom.js?v=2e6383b7:5264:5)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at SettingsObjectFieldDataType (SettingsObjectFieldDataType.tsx:58:3)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at a (<anonymous>)
    at LinkWithRef (react-router-dom.js?v=2e6383b7:5264:5)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at TableRow (TableRow.tsx:50:3)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at SettingsObjectFieldItemTableRow (SettingsObjectFieldItemTableRow.tsx:65:3)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at TableSection (TableSection.tsx:43:3)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at SettingsObjectFieldTable (SettingsObjectFieldTable.tsx:91:3)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at Section (Section.tsx:34:3)
    at ObjectFields (ObjectFields.tsx:17:32)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at ScrollWrapper (ScrollWrapper.tsx:35:3)
    at SettingsPageContainer (SettingsPageContainer.tsx:29:3)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at PagePanel (PagePanel.tsx:19:29)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at PageBody (PageBody.tsx:43:28)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at SubMenuTopBarContainer (SubMenuTopBarContainer.tsx:34:3)
    at SettingsObjectDetailPage (SettingsObjectDetailPage.tsx:68:20)
    at RenderedRoute (react-router-dom.js?v=2e6383b7:4035:5)
    at Routes (react-router-dom.js?v=2e6383b7:4474:5)
    at Suspense (<anonymous>)
    at SettingsRoutes (SettingsRoutes.tsx:253:3)
    at RenderedRoute (react-router-dom.js?v=2e6383b7:4035:5)
    at Outlet (react-router-dom.js?v=2e6383b7:4410:26)
    at ErrorBoundary (react-error-boundary.js?v=b04b1b36:18:5)
    at AppErrorBoundary (AppErrorBoundary.tsx:7:36)
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at div (<anonymous>)
    at MotionComponent (framer-motion.js?v=04ecb17b:277:40)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at div (<anonymous>)
    at chunk-CXFQHRW6.js?v=553c9d71:1278:45
    at DefaultLayout (DefaultLayout.tsx:62:20)
    at RenderedRoute (react-router-dom.js?v=2e6383b7:4035:5)
    at Outlet (react-router-dom.js?v=2e6383b7:4410:26)
    at DialogManager (DialogManager.tsx:7:33)
    at DialogManagerScope (DialogManagerScope.tsx:11:3)
    at SnackBarProvider (SnackBarProvider.tsx:27:36)
    at ThemeContextProvider (ThemeContextProvider.tsx:14:3)
    at ThemeProvider2 (chunk-CXFQHRW6.js?v=553c9d71:1308:22)
    at AppThemeProvider (AppThemeProvider.tsx:12:36)
    at PrefetchDataProvider (PrefetchDataProvider.tsx:5:40)
    at RelationPickerScope (RelationPickerScope.tsx:11:3)
    at PreComputedChipGeneratorsProvider (PreComputedChipGeneratorsProvider.tsx:9:3)
    at ObjectMetadataItemsProvider (ObjectMetadataItemsProvider.tsx:11:3)
    at ApolloMetadataClientProvider (ApolloMetadataClientProvider.tsx:7:3)
    at AuthProvider (AuthProvider.tsx:7:32)
    at UserProvider (UserProvider.tsx:11:32)
    at ChromeExtensionSidecarProvider (ChromeExtensionSidecarProvider.tsx:25:8)
    at ClientConfigProvider (ClientConfigProvider.tsx:6:3)
    at ApolloProvider (@apollo_client.js?v=10e00024:161:19)
    at ApolloProvider (ApolloProvider.tsx:5:34)
    at AppRouterProviders (AppRouterProviders.tsx:25:24)
    at RenderedRoute (react-router-dom.js?v=2e6383b7:4035:5)
    at RenderErrorBoundary (react-router-dom.js?v=2e6383b7:3995:5)
    at DataRoutes (react-router-dom.js?v=2e6383b7:5154:5)
    at Router (react-router-dom.js?v=2e6383b7:4417:15)
    at RouterProvider (react-router-dom.js?v=2e6383b7:4969:5)
    at AppRouter (AppRouter.tsx:8:19)
    at r2 (react-helmet-async.js?v=604e1fcc:387:21)
    at ExceptionHandlerProvider (ExceptionHandlerProvider.tsx:4:3)
    at IconsProvider (IconsProvider.tsx:10:33)
    at SnackBarProviderScope (SnackBarProviderScope.tsx:11:3)
    at CaptchaProvider (CaptchaProvider.tsx:5:35)
    at ErrorBoundary (react-error-boundary.js?v=b04b1b36:18:5)
    at AppErrorBoundary (AppErrorBoundary.tsx:7:36)
    at RecoilRoot_INTERNAL (recoil.js?v=a4e39a9b:2795:3)
    at RecoilRoot (recoil.js?v=a4e39a9b:2913:5)

**Comment by BOHEUS** [comment]
@FelixMalfait I reported it earlier in #8298

**Comment by FelixMalfait** [comment]
Thanks @BOHEUS!
