### ISSUE TITLE
Missing FROM-clause entry for table "_rocket"

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8661]
**Scenario:**
1. Log in
2. Go to Settings > Data model or go to Rockets tab

**Actual:** `Missing FROM-clause entry for table "_rocket"` error in logs appear

**Expected:** No error appears in logs when checking Data model tab

**Error:**
```
query failed: SELECT "rocket"."id" AS "rocket_id", "rocket"."name" AS "rocket_name", "rocket"."createdAt" AS "rocket_createdAt", "rocket"."updatedAt" AS "rocket_updatedAt", "rocket"."deletedAt" AS "rocket_deletedAt", "rocket"."createdBySource" AS "rocket_createdBySource", "rocket"."createdByWorkspaceMemberId" AS "rocket_createdByWorkspaceMemberId", "rocket"."createdByName" AS "rocket_createdByName", "rocket"."position" AS "rocket_position", "rocket"."searchVector" AS "rocket_searchVector" FROM "workspace_1wgvd1injqtife6y4rvfbu3h5"."_rocket" "rocket" WHERE "rocket"."deletedAt" IS NULL ORDER BY "_rocket"."id" ASC NULLS FIRST LIMIT 61
 error: error: missing FROM-clause entry for table "_rocket"
 Exception Captured
   {
     operation: { name: 'CombinedFindManyRecords', type: 'query' },
     document: 'query CombinedFindManyRecords($filterCompany: CompanyFilterInput, $filterNote: NoteFilterInput, $filterOpportunity: OpportunityFilterInput, $filterPerson: PersonFilterInput, $filterRocket: RocketFilterInput, $filterTask: TaskFilterInput, $filterWorkflow: WorkflowFilterInput, $filterWorkflowRun: WorkflowRunFilterInput, $filterWorkflowVersion: WorkflowVersionFilterInput, $orderByCompany: [CompanyOrderByInput], $orderByNote: [NoteOrderByInput], $orderByOpportunity: [OpportunityOrderByInput], $orderByPerson: [PersonOrderByInput], $orderByRocket: [RocketOrderByInput], $orderByTask: [TaskOrderByInput], $orderByWorkflow: [WorkflowOrderByInput], $orderByWorkflowRun: [WorkflowRunOrderByInput], $orderByWorkflowVersion: [WorkflowVersionOrderByInput], $lastCursorCompany: String, $lastCursorNote: String, $lastCursorOpportunity: String, $lastCursorPerson: String, $lastCursorRocket: String, $lastCursorTask: String, $lastCursorWorkflow: String, $lastCursorWorkflowRun: String, $lastCursorWorkflowVersion: String, $limitCompany: Int, $limitNote: Int, $limitOpportunity: Int, $limitPerson: Int, $limitRocket: Int, $limitTask: Int, $limitWorkflow: Int, $limitWorkflowRun: Int, $limitWorkflowVersion: Int) {\n' +
       '  companies(\n' +
       '    filter: $filterCompany\n' +
       '    orderBy: $orderByCompany\n' +
       '    first: $limitCompany\n' +
       '    after: $lastCursorCompany\n' +
       '  ) {\n' +
       '    edges {\n' +
       '      node {\n' +
       '        __typename\n' +
       '        id\n' +
       '      }\n' +
       '      cursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    pageInfo {\n' +
       '      hasNextPage\n' +
       '      hasPreviousPage\n' +
       '      startCursor\n' +
       '      endCursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    totalCount\n' +
       '    __typename\n' +
       '  }\n' +
       '  notes(\n' +
       '    filter: $filterNote\n' +
       '    orderBy: $orderByNote\n' +
       '    first: $limitNote\n' +
       '    after: $lastCursorNote\n' +
       '  ) {\n' +
       '    edges {\n' +
       '      node {\n' +
       '        __typename\n' +
       '        id\n' +
       '      }\n' +
       '      cursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    pageInfo {\n' +
       '      hasNextPage\n' +
       '      hasPreviousPage\n' +
       '      startCursor\n' +
       '      endCursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    totalCount\n' +
       '    __typename\n' +
       '  }\n' +
       '  opportunities(\n' +
       '    filter: $filterOpportunity\n' +
       '    orderBy: $orderByOpportunity\n' +
       '    first: $limitOpportunity\n' +
       '    after: $lastCursorOpportunity\n' +
       '  ) {\n' +
       '    edges {\n' +
       '      node {\n' +
       '        __typename\n' +
       '        id\n' +
       '      }\n' +
       '      cursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    pageInfo {\n' +
       '      hasNextPage\n' +
       '      hasPreviousPage\n' +
       '      startCursor\n' +
       '      endCursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    totalCount\n' +
       '    __typename\n' +
       '  }\n' +
       '  people(\n' +
       '    filter: $filterPerson\n' +
       '    orderBy: $orderByPerson\n' +
       '    first: $limitPerson\n' +
       '    after: $lastCursorPerson\n' +
       '  ) {\n' +
       '    edges {\n' +
       '      node {\n' +
       '        __typename\n' +
       '        id\n' +
       '      }\n' +
       '      cursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    pageInfo {\n' +
       '      hasNextPage\n' +
       '      hasPreviousPage\n' +
       '      startCursor\n' +
       '      endCursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    totalCount\n' +
       '    __typename\n' +
       '  }\n' +
       '  rockets(\n' +
       '    filter: $filterRocket\n' +
       '    orderBy: $orderByRocket\n' +
       '    first: $limitRocket\n' +
       '    after: $lastCursorRocket\n' +
       '  ) {\n' +
       '    edges {\n' +
       '      node {\n' +
       '        __typename\n' +
       '        id\n' +
       '      }\n' +
       '      cursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    pageInfo {\n' +
       '      hasNextPage\n' +
       '      hasPreviousPage\n' +
       '      startCursor\n' +
       '      endCursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    totalCount\n' +
       '    __typename\n' +
       '  }\n' +
       '  tasks(\n' +
       '    filter: $filterTask\n' +
       '    orderBy: $orderByTask\n' +
       '    first: $limitTask\n' +
       '    after: $lastCursorTask\n' +
       '  ) {\n' +
       '    edges {\n' +
       '      node {\n' +
       '        __typename\n' +
       '        id\n' +
       '      }\n' +
       '      cursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    pageInfo {\n' +
       '      hasNextPage\n' +
       '      hasPreviousPage\n' +
       '      startCursor\n' +
       '      endCursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    totalCount\n' +
       '    __typename\n' +
       '  }\n' +
       '  workflows(\n' +
       '    filter: $filterWorkflow\n' +
       '    orderBy: $orderByWorkflow\n' +
       '    first: $limitWorkflow\n' +
       '    after: $lastCursorWorkflow\n' +
       '  ) {\n' +
       '    edges {\n' +
       '      node {\n' +
       '        __typename\n' +
       '        id\n' +
       '      }\n' +
       '      cursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    pageInfo {\n' +
       '      hasNextPage\n' +
       '      hasPreviousPage\n' +
       '      startCursor\n' +
       '      endCursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    totalCount\n' +
       '    __typename\n' +
       '  }\n' +
       '  workflowRuns(\n' +
       '    filter: $filterWorkflowRun\n' +
       '    orderBy: $orderByWorkflowRun\n' +
       '    first: $limitWorkflowRun\n' +
       '    after: $lastCursorWorkflowRun\n' +
       '  ) {\n' +
       '    edges {\n' +
       '      node {\n' +
       '        __typename\n' +
       '        id\n' +
       '      }\n' +
       '      cursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    pageInfo {\n' +
       '      hasNextPage\n' +
       '      hasPreviousPage\n' +
       '      startCursor\n' +
       '      endCursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    totalCount\n' +
       '    __typename\n' +
       '  }\n' +
       '  workflowVersions(\n' +
       '    filter: $filterWorkflowVersion\n' +
       '    orderBy: $orderByWorkflowVersion\n' +
       '    first: $limitWorkflowVersion\n' +
       '    after: $lastCursorWorkflowVersion\n' +
       '  ) {\n' +
       '    edges {\n' +
       '      node {\n' +
       '        __typename\n' +
       '        id\n' +
       '      }\n' +
       '      cursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    pageInfo {\n' +
       '      hasNextPage\n' +
       '      hasPreviousPage\n' +
       '      startCursor\n' +
       '      endCursor\n' +
       '      __typename\n' +
       '    }\n' +
       '    totalCount\n' +
       '    __typename\n' +
       '  }\n' +
       '}',
     user: User {
       id: '20202020-9e3b-46d4-a556-88b9ddc2b034',
       firstName: 'Tim',
       lastName: 'Apple',
       email: 'tim@apple.dev',
       defaultAvatarUrl: null,
       emailVerified: false,
       disabled: false,
       passwordHash: '$2b$10$66d.6DuQExxnrfI9rMqOg.U1XIYpagr6Lv05uoWLYbYmtK0HDIvS6',
       canImpersonate: false,
       createdAt: 2024-11-21T19:31:04.421Z,
       updatedAt: 2024-11-21T19:31:04.421Z,
       deletedAt: null,
       defaultWorkspaceId: '20202020-1c25-4d02-bf25-6aeccf7ea419'
     }
   }
   [
     QueryFailedError: missing FROM-clause entry for table "_rocket"
         at PostgresQueryRunner.query (/home/user/Desktop/projects/twenty/src/driver/postgres/PostgresQueryRunner.ts:331:19)
         at processTicksAndRejections (node:internal/process/task_queues:95:5)
         at SelectQueryBuilder.loadRawResults (/home/user/Desktop/projects/twenty/src/query-builder/SelectQueryBuilder.ts:3805:25)
         at SelectQueryBuilder.executeEntitiesAndRawResults (/home/user/Desktop/projects/twenty/src/query-builder/SelectQueryBuilder.ts:3551:26)
         at SelectQueryBuilder.getRawAndEntities (/home/user/Desktop/projects/twenty/src/query-builder/SelectQueryBuilder.ts:1670:29)
         at SelectQueryBuilder.getMany (/home/user/Desktop/projects/twenty/src/query-builder/SelectQueryBuilder.ts:1760:25)
         at GraphqlQueryFindManyResolverService.resolve (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-many-resolver.service.ts:142:39)
         at GraphqlQueryFindManyResolverService.execute (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/api/graphql/graphql-query-runner/interfaces/base-resolver-service.ts:109:21)
         at Object.rockets (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/find-many-resolver.factory.ts:39:16)
         at field.resolve (/home/user/Desktop/projects/twenty/node_modules/@envelop/on-resolve/cjs/index.js:36:42) {
       path: undefined,
       locations: undefined,
       extensions: {
         code: 'INTERNAL_SERVER_ERROR',
         response: 'missing FROM-clause entry for table "_rocket"'
       }
     }
   ]
```

**Comment by ehconitin** [comment]
@BOHEUS this is fixed ig!

**Comment by BOHEUS** [comment]
@ehconitin yes, it is, I can't reproduce it
