### ISSUE TITLE
Can't create any record

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8662]
**Scenario:**
1. Log in
2. Go to any records tab (e.g. People tab)
3. Try to create a new record

**Actual:** There's error in UI and also in logs while creating new records and preventing from creating
[Video](https://github.com/user-attachments/assets/c872efa3-f9af-40bb-a4e6-de35f1a8ae0a)

**Expected:** Records must be created like earlier

**Error:**
```
 query failed: INSERT INTO "workspace_1wgvd1injqtife6y4rvfbu3h5"."opportunity"("deletedAt", "pointOfContactId", "companyId", "name", "amountAmountMicros", "amountCurrencyCode", "closeDate", "stage", "position", "createdBySource", "createdByWorkspaceMemberId", "createdByName", "searchVector", "id", "createdAt", "updatedAt") VALUES (DEFAULT, DEFAULT, $1, $2, DEFAULT, DEFAULT, DEFAULT, $3, $4, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $5, DEFAULT, DEFAULT) RETURNING "deletedAt", "name", "amountAmountMicros", "amountCurrencyCode", "closeDate", "stage", "position", "createdBySource", "createdByWorkspaceMemberId", "createdByName", "searchVector", "id", "createdAt", "updatedAt" -- PARAMETERS: ["20202020-171e-4bcc-9cf7-43448d6fb278","Airbnb","NEW","first","e69db9ad-34af-45e0-9b6a-cb58ba29729a"]
 error: error: invalid input syntax for type double precision: "first"
 Exception Captured
   {
     operation: { name: 'CreateOneOpportunity', type: 'mutation' },
     document: 'mutation CreateOneOpportunity($input: OpportunityCreateInput!) {\n' +
       '  createOpportunity(data: $input) {\n' +
       '    __typename\n' +
       '    amount {\n' +
       '      amountMicros\n' +
       '      currencyCode\n' +
       '      __typename\n' +
       '    }\n' +
       '    attachments {\n' +
       '      edges {\n' +
       '        node {\n' +
       '          __typename\n' +
       '          authorId\n' +
       '          companyId\n' +
       '          createdAt\n' +
       '          deletedAt\n' +
       '          fullPath\n' +
       '          id\n' +
       '          name\n' +
       '          noteId\n' +
       '          opportunityId\n' +
       '          personId\n' +
       '          rocketId\n' +
       '          taskId\n' +
       '          type\n' +
       '          updatedAt\n' +
       '        }\n' +
       '        __typename\n' +
       '      }\n' +
       '      __typename\n' +
       '    }\n' +
       '    closeDate\n' +
       '    company {\n' +
       '      __typename\n' +
       '      accountOwnerId\n' +
       '      address {\n' +
       '        addressStreet1\n' +
       '        addressStreet2\n' +
       '        addressCity\n' +
       '        addressState\n' +
       '        addressCountry\n' +
       '        addressPostcode\n' +
       '        addressLat\n' +
       '        addressLng\n' +
       '        __typename\n' +
       '      }\n' +
       '      annualRecurringRevenue {\n' +
       '        amountMicros\n' +
       '        currencyCode\n' +
       '        __typename\n' +
       '      }\n' +
       '      createdAt\n' +
       '      createdBy {\n' +
       '        source\n' +
       '        workspaceMemberId\n' +
       '        name\n' +
       '        __typename\n' +
       '      }\n' +
       '      deletedAt\n' +
       '      domainName {\n' +
       '        primaryLinkUrl\n' +
       '        primaryLinkLabel\n' +
       '        secondaryLinks\n' +
       '        __typename\n' +
       '      }\n' +
       '      employees\n' +
       '      id\n' +
       '      idealCustomerProfile\n' +
       '      introVideo {\n' +
       '        primaryLinkUrl\n' +
       '        primaryLinkLabel\n' +
       '        secondaryLinks\n' +
       '        __typename\n' +
       '      }\n' +
       '      linkedinLink {\n' +
       '        primaryLinkUrl\n' +
       '        primaryLinkLabel\n' +
       '        secondaryLinks\n' +
       '        __typename\n' +
       '      }\n' +
       '      name\n' +
       '      position\n' +
       '      tagline\n' +
       '      updatedAt\n' +
       '      visaSponsorship\n' +
       '      workPolicy\n' +
       '      xLink {\n' +
       '        primaryLinkUrl\n' +
       '        primaryLinkLabel\n' +
       '        secondaryLinks\n' +
       '        __typename\n' +
       '      }\n' +
       '    }\n' +
       '    companyId\n' +
       '    createdAt\n' +
       '    createdBy {\n' +
       '      source\n' +
       '      workspaceMemberId\n' +
       '      name\n' +
       '      __typename\n' +
       '    }\n' +
       '    deletedAt\n' +
       '    favorites {\n' +
       '      edges {\n' +
       '        node {\n' +
       '          __typename\n' +
       '          companyId\n' +
       '          createdAt\n' +
       '          deletedAt\n' +
       '          favoriteFolderId\n' +
       '          id\n' +
       '          noteId\n' +
       '          opportunityId\n' +
       '          personId\n' +
       '          position\n' +
       '          rocketId\n' +
       '          taskId\n' +
       '          updatedAt\n' +
       '          viewId\n' +
       '          workflowId\n' +
       '          workflowRunId\n' +
       '          workflowVersionId\n' +
       '          workspaceMemberId\n' +
       '        }\n' +
       '        __typename\n' +
       '      }\n' +
       '      __typename\n' +
       '    }\n' +
       '    id\n' +
       '    name\n' +
       '    noteTargets {\n' +
       '      edges {\n' +
       '        node {\n' +
       '          __typename\n' +
       '          companyId\n' +
       '          createdAt\n' +
       '          deletedAt\n' +
       '          id\n' +
       '          noteId\n' +
       '          opportunityId\n' +
       '          personId\n' +
       '          rocketId\n' +
       '          updatedAt\n' +
       '        }\n' +
       '        __typename\n' +
       '      }\n' +
       '      __typename\n' +
       '    }\n' +
       '    pointOfContact {\n' +
       '      __typename\n' +
       '      avatarUrl\n' +
       '      city\n' +
       '      companyId\n' +
       '      createdAt\n' +
       '      createdBy {\n' +
       '        source\n' +
       '        workspaceMemberId\n' +
       '        name\n' +
       '        __typename\n' +
       '      }\n' +
       '      deletedAt\n' +
       '      emails {\n' +
       '        primaryEmail\n' +
       '        additionalEmails\n' +
       '        __typename\n' +
       '      }\n' +
       '      id\n' +
       '      intro\n' +
       '      jobTitle\n' +
       '      linkedinLink {\n' +
       '        primaryLinkUrl\n' +
       '        primaryLinkLabel\n' +
       '        secondaryLinks\n' +
       '        __typename\n' +
       '      }\n' +
       '      name {\n' +
       '        firstName\n' +
       '        lastName\n' +
       '        __typename\n' +
       '      }\n' +
       '      performanceRating\n' +
       '      phones {\n' +
       '        primaryPhoneNumber\n' +
       '        primaryPhoneCountryCode\n' +
       '        additionalPhones\n' +
       '        __typename\n' +
       '      }\n' +
       '      position\n' +
       '      updatedAt\n' +
       '      whatsapp {\n' +
       '        primaryPhoneNumber\n' +
       '        primaryPhoneCountryCode\n' +
       '        additionalPhones\n' +
       '        __typename\n' +
       '      }\n' +
       '      workPreference\n' +
       '      xLink {\n' +
       '        primaryLinkUrl\n' +
       '        primaryLinkLabel\n' +
       '        secondaryLinks\n' +
       '        __typename\n' +
       '      }\n' +
       '    }\n' +
       '    pointOfContactId\n' +
       '    position\n' +
       '    stage\n' +
       '    taskTargets {\n' +
       '      edges {\n' +
       '        node {\n' +
       '          __typename\n' +
       '          companyId\n' +
       '          createdAt\n' +
       '          deletedAt\n' +
       '          id\n' +
       '          opportunityId\n' +
       '          personId\n' +
       '          rocketId\n' +
       '          taskId\n' +
       '          updatedAt\n' +
       '        }\n' +
       '        __typename\n' +
       '      }\n' +
       '      __typename\n' +
       '    }\n' +
       '    timelineActivities {\n' +
       '      edges {\n' +
       '        node {\n' +
       '          __typename\n' +
       '          companyId\n' +
       '          createdAt\n' +
       '          deletedAt\n' +
       '          happensAt\n' +
       '          id\n' +
       '          linkedObjectMetadataId\n' +
       '          linkedRecordCachedName\n' +
       '          linkedRecordId\n' +
       '          name\n' +
       '          noteId\n' +
       '          opportunityId\n' +
       '          personId\n' +
       '          properties\n' +
       '          rocketId\n' +
       '          taskId\n' +
       '          updatedAt\n' +
       '          workflowId\n' +
       '          workflowRunId\n' +
       '          workflowVersionId\n' +
       '          workspaceMemberId\n' +
       '        }\n' +
       '        __typename\n' +
       '      }\n' +
       '      __typename\n' +
       '    }\n' +
       '    updatedAt\n' +
       '  }\n' +
       '}',
     user: User {
       id: '20202020-9e3b-46d4-a556-88b9ddc2b034',
       firstName: 'Tim',
       lastName: 'Apple',
       email: 'tim@apple.dev',
       defaultAvatarUrl: null,
       emailVerified: false,
       disabled: false,
       passwordHash: '$2b$10$66d.6DuQExxnrfI9rMqOg.U1XIYpagr6Lv05uoWLYbYmtK0HDIvS6',
       canImpersonate: false,
       createdAt: 2024-11-21T19:31:04.421Z,
       updatedAt: 2024-11-21T19:31:04.421Z,
       deletedAt: null,
       defaultWorkspaceId: '20202020-1c25-4d02-bf25-6aeccf7ea419'
     }
   }
   [
     QueryFailedError: invalid input syntax for type double precision: "first"
         at PostgresQueryRunner.query (/home/user/Desktop/projects/twenty/src/driver/postgres/PostgresQueryRunner.ts:331:19)
         at processTicksAndRejections (node:internal/process/task_queues:95:5)
         at InsertQueryBuilder.execute (/home/user/Desktop/projects/twenty/src/query-builder/InsertQueryBuilder.ts:163:33)
         at WorkspaceRepository.insert (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/twenty-orm/repository/workspace.repository.ts:425:20)
         at GraphqlQueryCreateOneResolverService.resolve (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-create-one-resolver.service.ts:32:9)
         at GraphqlQueryCreateOneResolverService.execute (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/api/graphql/graphql-query-runner/interfaces/base-resolver-service.ts:109:21)
         at Object.createOpportunity (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/create-one-resolver.factory.ts:39:16)
         at field.resolve (/home/user/Desktop/projects/twenty/node_modules/@envelop/on-resolve/cjs/index.js:36:42)
         at /home/user/Desktop/projects/twenty/node_modules/@envelop/core/cjs/orchestrator.js:383:27
         at YogaServer.getResultForParams (/home/user/Desktop/projects/twenty/node_modules/graphql-yoga/cjs/server.js:304:26) {
       path: undefined,
       locations: undefined,
       extensions: {
         code: 'INTERNAL_SERVER_ERROR',
         response: 'invalid input syntax for type double precision: "first"'
       }
     }
   ]
```

**Comment by FelixMalfait** [comment]
Fixed in 33.1. Thanks for the report!
