### ISSUE TITLE
Fresh setup of PostgreSQL database Docker container fails

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8701]
As I transitioned from old Postgres bitnami container to new Postgres spilo container as it's mentioned in [docs](https://twenty.com/developers/local-setup#step-3:-set-up-a-postgresql-database), I stumped upon error when running `npx nx database:reset twenty-server`. It turns out that script responsible for resetting database and configuring it, has problem with creating new user. 

Here's my workaround:
- `docker exec -it twenty_pg bash` to access directly container's console
- `psql postgres -c "CREATE DATABASE default;" -c "CREATE DATABASE test;" -c "CREATE USER twenty PASSWORD 'twenty';" -c "ALTER ROLE twenty superuser;"` taken from docs (if it doesn't work, run `psql -U postgres` and type each command separately)
After that, when running `npx nx database:reset twenty-server` worked fine like before

**Logs:**
```
> npx nx database:reset twenty-server

   ✔  1/1 dependent project tasks succeeded [1 read from cache]

   Hint: you can run the command with --verbose to see the full dependent project outputs

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


> nx run twenty-server:build  [local cache]

> rimraf dist

> nest build --path ./tsconfig.build.json

-  TSC  Initializing type checker...
✔  TSC  Initializing type checker...
>  TSC  Found 0 issues.
>  SWC  Running...
Successfully compiled: 1653 files with swc (707.62ms)

> nx run twenty-server:"database:reset"

> nx ts-node-no-deps -- ./scripts/truncate-db.ts


> nx run twenty-server:ts-node-no-deps ./scripts/truncate-db.ts

> ts-node ./scripts/truncate-db.ts

Error during schema dropping: error: password authentication failed for user "twenty"
    at Parser.parseErrorMessage (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 102,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '326',
  routine: 'auth_failed'
}

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Successfully ran target ts-node-no-deps for project twenty-server (7s)

      With additional flags:
        ./scripts/truncate-db.ts

> nx ts-node-no-deps -- ./scripts/setup-db.ts


> nx run twenty-server:ts-node-no-deps ./scripts/setup-db.ts

> ts-node ./scripts/setup-db.ts

Error during Data Source initialization: error: password authentication failed for user "twenty"
    at Parser.parseErrorMessage (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 102,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '326',
  routine: 'auth_failed'
}

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Successfully ran target ts-node-no-deps for project twenty-server (6s)

      With additional flags:
        ./scripts/setup-db.ts

> nx database:migrate


   ✔  1/1 dependent project tasks succeeded [1 read from cache]

   Hint: you can run the command with --verbose to see the full dependent project outputs

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


> nx run twenty-server:build  [existing outputs match the cache, left as is]

> rimraf dist

> nest build --path ./tsconfig.build.json

-  TSC  Initializing type checker...
✔  TSC  Initializing type checker...
>  TSC  Found 0 issues.
>  SWC  Running...
Successfully compiled: 1653 files with swc (707.62ms)

> nx run twenty-server:"database:migrate"

> nx typeorm -- migration:run -d src/database/typeorm/metadata/metadata.datasource


> nx run twenty-server:typeorm migration:run -d src/database/typeorm/metadata/metadata.datasource

> ts-node ../../node_modules/typeorm/cli.js migration:run -d src/database/typeorm/metadata/metadata.datasource

Error during migration run:
error: password authentication failed for user "twenty"
    at Parser.parseErrorMessage (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 102,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '326',
  routine: 'auth_failed'
}
Warning: command "ts-node ../../node_modules/typeorm/cli.js migration:run -d src/database/typeorm/metadata/metadata.datasource" exited with non-zero status code
——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target typeorm for project twenty-server (829ms)

      With additional flags:
        migration:run
        --d=src/database/typeorm/metadata/metadata.datasource

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]

Warning: command "nx typeorm -- migration:run -d src/database/typeorm/metadata/metadata.datasource" exited with non-zero status code
——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target database:migrate for project twenty-server and 2 task(s) they depend on (1s)

   ✖  1/3 failed
   ✔  2/3 succeeded [2 read from cache]

Warning: command "nx database:migrate" exited with non-zero status code
——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target database:reset for project twenty-server and 2 task(s) they depend on (14s)

   ✖  1/3 failed
   ✔  2/3 succeeded [2 read from cache]

➜  twenty git:(6638_authorization_token_env) ✗ npx nx database:reset twenty-server

   ✔  1/1 dependent project tasks succeeded [1 read from cache]

   Hint: you can run the command with --verbose to see the full dependent project outputs

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


> nx run twenty-server:build  [existing outputs match the cache, left as is]

> rimraf dist

> nest build --path ./tsconfig.build.json

-  TSC  Initializing type checker...
✔  TSC  Initializing type checker...
>  TSC  Found 0 issues.
>  SWC  Running...
Successfully compiled: 1653 files with swc (707.62ms)

> nx run twenty-server:"database:reset"

> nx ts-node-no-deps -- ./scripts/truncate-db.ts


> nx run twenty-server:ts-node-no-deps ./scripts/truncate-db.ts

> ts-node ./scripts/truncate-db.ts

Error during schema dropping: error: password authentication failed for user "twenty"
    at Parser.parseErrorMessage (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 102,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '326',
  routine: 'auth_failed'
}

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Successfully ran target ts-node-no-deps for project twenty-server (6s)

      With additional flags:
        ./scripts/truncate-db.ts

> nx ts-node-no-deps -- ./scripts/setup-db.ts


> nx run twenty-server:ts-node-no-deps ./scripts/setup-db.ts

> ts-node ./scripts/setup-db.ts

Error during Data Source initialization: error: password authentication failed for user "twenty"
    at Parser.parseErrorMessage (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 102,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '326',
  routine: 'auth_failed'
}

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Successfully ran target ts-node-no-deps for project twenty-server (6s)

      With additional flags:
        ./scripts/setup-db.ts

> nx database:migrate


   ✔  1/1 dependent project tasks succeeded [1 read from cache]

   Hint: you can run the command with --verbose to see the full dependent project outputs

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


> nx run twenty-server:build  [existing outputs match the cache, left as is]

> rimraf dist

> nest build --path ./tsconfig.build.json

-  TSC  Initializing type checker...
✔  TSC  Initializing type checker...
>  TSC  Found 0 issues.
>  SWC  Running...
Successfully compiled: 1653 files with swc (707.62ms)

> nx run twenty-server:"database:migrate"

> nx typeorm -- migration:run -d src/database/typeorm/metadata/metadata.datasource


> nx run twenty-server:typeorm migration:run -d src/database/typeorm/metadata/metadata.datasource

> ts-node ../../node_modules/typeorm/cli.js migration:run -d src/database/typeorm/metadata/metadata.datasource

Error during migration run:
error: password authentication failed for user "twenty"
    at Parser.parseErrorMessage (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/user/Desktop/projects/twenty/node_modules/pg/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 102,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '326',
  routine: 'auth_failed'
}
Warning: command "ts-node ../../node_modules/typeorm/cli.js migration:run -d src/database/typeorm/metadata/metadata.datasource" exited with non-zero status code
——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target typeorm for project twenty-server (814ms)

      With additional flags:
        migration:run
        --d=src/database/typeorm/metadata/metadata.datasource

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]

Warning: command "nx typeorm -- migration:run -d src/database/typeorm/metadata/metadata.datasource" exited with non-zero status code
——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target database:migrate for project twenty-server and 2 task(s) they depend on (1s)

   ✖  1/3 failed
   ✔  2/3 succeeded [2 read from cache]

Warning: command "nx database:migrate" exited with non-zero status code
——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target database:reset for project twenty-server and 2 task(s) they depend on (13s)

   ✖  1/3 failed
   ✔  2/3 succeeded [2 read from cache]
```

**Comment by Bonapara** [comment]
@BOHEUS did you experienced it again since then? Thanks for reporting it!

**Comment by BOHEUS** [comment]
@Bonapara no as I set it up and I haven't touched it since ("if it's working, don't touch it" 😆)

**Comment by charlesBochet** [comment]
@prastoin could you take a look at this one?

**Comment by prastoin** [comment]
Hello there, I remember encountering the very much pattern when initializing my local setup a while ago.
Thing is by default psql user `twenty` does not exist, the default superuser created by psql will follow current /home or window's profile name. e.g `prastoin`.
I think we should add to the docs a line regarding `twenty` or `postgres` superuser in order to avoid this to reoccur ?

@charlesBochet what do you think ?

**Comment by charlesBochet** [comment]
Tagging this as good first issue

**Comment by tehnuge** [comment]
Hello, I'm trying a new, fresh setup of Twenty and am running into an issue trying the 1 click docker compose command raised after trying to start the `twenty-server` container:
```
[Nest] 1  - 04/17/2025, 1:35:26 AM   ERROR [TypeOrmModule] Unable to connect to the database (metadata). Retrying (1)...
error: password authentication failed for user "postgres"
    at Parser.parseErrorMessage (/app/node_modules/pg/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/app/node_modules/pg/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/app/node_modules/pg/node_modules/pg-protocol/dist/parser.js:35:38)
    at Socket.<anonymous> (/app/node_modules/pg/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```
Is this related? Would anyone be able to point to how I could resolve it?

**Comment by charlesBochet** [comment]
Hi @tehnuge, regarding setup issue, please reach out on our Discord server, the community will be able to assist from there

**Comment by prastoin** [comment]
@charlesBochet we should address this as many self hosters are encountering the issue but aren't able to debug their postgres authentication agnostically of Twenty
We could either add some documentation or at least programmatically check that postgres users exists

**Comment by ERipperda** [comment]
Hello Twenty community,
 
My team and I are interested in fixing this issue (@StormNinja17 @kateende @benjamintowle04 @mbae0). We want to confirm that to fix this issue, we will: 

- Identify if a user exists in the entrypoint.sh file
- If user does not exist, create user

Is that all? Are there other recommendations?

Regards, 
Eli

**Comment by StormNinja17** [comment]
@prastoin  ,
Thank you for the clarification! Our team would love to look into this and try to find a solution. Could we get this issue assigned to one of our team members?

**Comment by prastoin** [comment]
No worries, yep here you are

**Comment by StormNinja17** [comment]
@prastoin Our team added a couple automated checks to entrypoint.sh and updated the documentation. We were not able to directly reproduce the original issue, but we think these checks should help in flagging an issue during database setup. Let us know if we need to change anything or if there's something you would like to see different.

Our PR is #11759.

**Comment by Mang0codes** [comment]
If this issue hasn't been resolved yet, I'd like to take it on.

**Comment by prastoin** [comment]
> If this issue hasn't been resolved yet, I'd like to take it on.

Hello @Mang0codes, sorry this issue is unavailable

**Comment by prastoin** [comment]
Taking this

**Comment by titouan13** [comment]
Using the one-line script install, it doesn't work.

I have this error (with or without custom password in .env file):
`server-1  | psql: error: connection to server at "db" (172.20.0.3), port 5432 failed: FATAL:  password authentication failed for user "postgres"`

Changing the user doesn't change anything.

Of course I tried several times this method: https://docs.twenty.com/developers/self-host/capabilities/troubleshooting#first-install-results-in-password-authentication-failed-for-user-%22postgres%22


EDIT: After restarting the app, it worked (it seems random). But in the logs, I still have
`worker-1  | Error: Failed to load all config variables: password authentication failed for user "postgres"
server-1  | Error: Failed to load all config variables: password authentication failed for user "postgres"
`
