### ISSUE TITLE
If the goal is to get people to not self host, you're doing great!

### ISSUE THREAD

**Issue by WoahitsJoe** [twentyhq/twenty#8821]
## Bug Description

A clear and concise description of what the current behavior is.
Please also add **screenshots** of the existing application.

```
Current new user experience -
Try to use provided k8s manifest, not working. Try to convert docker compose to k8s manifests, not working.
Try to use https://twenty.com/developers/section/self-hosting/docker-compose -> bash <(curl -sL https://git.new/20) -> works, but pulls version 0.33.0, so you can't create tasks as you get this problem https://github.com/twentyhq/twenty/issues/8797 = not working

Set the branch to the latest tag (0.33.5). > VERSION=v0.33.5 BRANCH=main bash <(curl -sL https://git.new/20)
Doesn't work,  error  "✘ worker Error manifest for twentycrm/twenty:v0.33.5 not found: manifest unknown: manifest unknown" = not working

Let's try 0.33.4. Works. Wow.
create test workspace -> create test user -> no email sync -> create 1 test task-> creates api token -> curls api for default users user id -> tries to make a task via api ->

curl --request POST \
  --url http://host.docker.internal:3000/rest/tasks \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjEyY2JjZC1lMThiLTRlMGItOTkwNC0xZjg4ZWZlMmQ5N2UiLCJ0eXBlIjoiQVBJX0tFWSIsIndvcmtzcGFjZUlkIjoiM2IxMmNiY2QtZTE4Yi00ZTBiLTk5MDQtMWY4OGVmZTJkOTdlIiwiaWF0IjoxNzMyOTYxMDMwLCJleHAiOjQ4ODY1NjEwMjksImp0aSI6IjQzZjAzY2ZmLWZhMmEtNDViMC04NTliLTIxZWVkN2MzYWYzZiJ9.HkrVIeOJYarlZdL-GSwbVdRs9Mt7Cb7-TD7kQqbcnTY' \
  --header 'Content-Type: application/json' \
  --data '{
  "position": 2,
  "title": "string",
  "body": "string",
  "dueAt": "2025-08-24T11:00:00Z",
  "status": "TODO",
  "createdBy": {
    "source": "EMAIL"
  },
  "assigneeId": "4bcdb570-291d-45bf-9a88-c86fcb896f4e"
}'

Errors with - 
server-1  |     SyntaxError: Unexpected token s in JSON at position 0
server-1  |         at JSON.parse (<anonymous>)
server-1  |         at ActivityQueryResultGetterHandler.handle (/app/packages/twenty-server/dist/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/handlers/activity-query-result-getter.handler.js:16:27)
server-1  |         at QueryResultGettersFactory.processRecord (/app/packages/twenty-server/dist/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/query-result-getters.factory.js:97:74)
server-1  |         at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
server-1  |         at async QueryResultGettersFactory.processQueryResultField (/app/packages/twenty-server/dist/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/query-result-getters.factory.js:112:20)
server-1  |         at async QueryResultGettersFactory.create (/app/packages/twenty-server/dist/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/query-result-getters.factory.js:120:16)
server-1  |         at async GraphqlQueryCreateOneResolverService.execute (/app/packages/twenty-server/dist/src/engine/api/graphql/graphql-query-runner/interfaces/base-resolver-service.js:55:35)
server-1  |         at async Object.createTask (/app/packages/twenty-server/dist/src/engine/api/graphql/workspace-resolver-builder/factories/create-one-resolver.factory.js:34:24)
server-1  |         at async field.resolve (/app/node_modules/@envelop/on-resolve/cjs/index.js:36:42)
server-1  |         at async /app/node_modules/@envelop/core/cjs/orchestrator.js:383:27 {
server-1  |       path: undefined,
server-1  |       locations: undefined,
server-1  |       extensions: {
server-1  |         code: 'INTERNAL_SERVER_ERROR',
server-1  |         response: 'Unexpected token s in JSON at position 0'
server-1  |       }
server-1  |     }
server-1  |   ]

-> goes back to ui and cant create tasks or see the previously created test task = not working
```
![Image](https://github.com/user-attachments/assets/e3741aac-c30f-4a8e-8db5-889c20cbbf0c)

## Expected behavior

Things to work, k8s to work. Admin panel with roles.

**Comment by charlesBochet** [comment]
@WoahitsJoe You are surfacing several issues:

1) K8s configurations are not maintained by the core team but by community
2) Docker-compose 1 click set up has been recently changed, @FelixMalfait could you take a look?
3) Interacting with RICH_TEXT fields (we actually only use it for Tasks and Notes) through API is a bit tricky as you currently have to respect the proper Json format, we plan to improve this behavior before end of the year

**Comment by charlesBochet** [comment]
Keeping this issue open until we fix the docker-compose 1-click

**Comment by FelixMalfait** [comment]
Good feedback, thanks, will have a look tomorrow. Could just be put in a nicer way :)

**Comment by FelixMalfait** [comment]
OK the Error manifest is fixed, this was bad luck - we switched provider from Github Actions machines for the build and they had a downtime which led to 0.33.5 not being published

The tasks/note body field api will most likely be improved by EOY, @eliasylonen will likely work on it

**Comment by WoahitsJoe** [comment]
Thanks @FelixMalfait @charlesBochet was a little frustrated..
If I get k8s working, I'll get the public module updated for you guys

**Comment by FelixMalfait** [comment]
No worries @WoahitsJoe - thanks!
It's true that self-hosting isn't the #1 priority because we don't consider Twenty to be a good-enough tool for ourselves now so we preferred to focus on adding many new features and stabilizing the code base first rather than marketing a project that doesn't satisfy end-users.
The key to a great self-hosting experience is the stability of the underlying infra / code base and being an early stage project we kept coming back on decisions/refactoring to make the right long-term choices while we can still afford it. I think there will still be infra changes (we might add an _optional_ Kafka + Clickhouse in a year or so) but it should be more stable in 2025 than it was in 2024.
Let us know if you manage to make it work on k8s, that'd be great!
