### ISSUE TITLE
password authentication failed for user "postgres" (self hosted)

### ISSUE THREAD

**Issue by travmaxcloud** [twentyhq/twenty#9049]
i got error when i tried to connect with postgres database

error: password authentication failed for user "postgres"
    at Parser.parseErrorMessage (/app/node_modules/pg/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/app/node_modules/pg/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/app/node_modules/pg/node_modules/pg-protocol/dist/parser.js:35:38)
    at Socket.<anonymous> (/app/node_modules/pg/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

my connection string look like this

postgres://postgres:postgres@db:5432/twenty

i also used supabase remote database in that case app is working but in local environment it giving me "authentication error"

my postgres database is running on docker and working fine without any error and ready to accept connection 

i dont know why i am getting this error

**Comment by FelixMalfait** [comment]
Hello!
The `db` host in `postgres://postgres:postgres@db:5432/twenty` is in a docker-compose environment (it's the 'internal' url). From your message it's unclear what your setup really is but you might want to try a different url if your db is exposed publicly (you mention Supabase)
I think it will be hard to help you debug with that context
