### ISSUE TITLE
Broken installation with bash <(curl -sL https://git.new/20), shows "Unable to Reach Back-end"

### ISSUE THREAD

**Issue by Surakshanet** [twentyhq/twenty#9231]
## Bug Description

Missing value of SIGN_IN_PREFILLED in .env, as created by the install script, results in broken installation.

## Expected behavior

Functioning login screen at http://localhost:3000

## Technical inputs
Missing value of SIGN_IN_PREFILLED in .env

**Comment by HRT-Tech** [comment]
Exception Captured
  {
    operation: { name: 'GetClientConfig', type: 'query' },
    document: 'query GetClientConfig {\n' +
      '  clientConfig {\n' +
      '    billing {\n' +
      '      isBillingEnabled\n' +
      '      billingUrl\n' +
      '      billingFreeTrialDurationInDays\n' +
      '      __typename\n' +
      '    }\n' +
      '    authProviders {\n' +
      '      google\n' +
      '      password\n' +
      '      microsoft\n' +
      '      sso {\n' +
      '        id\n' +
      '        name\n' +
      '        type\n' +
      '        status\n' +
      '        issuer\n' +
      '        __typename\n' +
      '      }\n' +
      '      __typename\n' +
      '    }\n' +
      '    signInPrefilled\n' +
      '    isMultiWorkspaceEnabled\n' +
      '    isSSOEnabled\n' +
      '    defaultSubdomain\n' +
      '    frontDomain\n' +
      '    debugMode\n' +
      '    analyticsEnabled\n' +
      '    support {\n' +
      '      supportDriver\n' +
      '      supportFrontChatId\n' +
      '      __typename\n' +
      '    }\n' +
      '    sentry {\n' +
      '      dsn\n' +
      '      environment\n' +
      '      release\n' +
      '      __typename\n' +
      '    }\n' +
      '    captcha {\n' +
      '      provider\n' +
      '      siteKey\n' +
      '      __typename\n' +
      '    }\n' +
      '    api {\n' +
      '      mutationMaximumAffectedRecords\n' +
      '      __typename\n' +
      '    }\n' +
      '    chromeExtensionId\n' +
      '    __typename\n' +
      '  }\n' +
      '}',
    user: undefined,
    workspace: {
      id: undefined,
      displayName: undefined,
      createdAt: undefined,
      activationStatus: undefined
    }
  }
  [
    Error: Boolean cannot represent a non boolean value: ""
        at completeLeafValue (/app/node_modules/@graphql-tools/executor/cjs/execution/execute.js:620:19)
        at completeValue (/app/node_modules/@graphql-tools/executor/cjs/execution/execute.js:451:16)
        at completeValue (/app/node_modules/@graphql-tools/executor/cjs/execution/execute.js:434:27)
        at /app/node_modules/@graphql-tools/executor/cjs/execution/execute.js:327:49
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async /app/node_modules/@graphql-tools/executor/cjs/execution/promiseForObject.js:18:35
        at async Promise.all (index 2) {
      path: undefined,
      locations: undefined,
      extensions: {
        code: 'INTERNAL_SERVER_ERROR',
        response: 'Boolean cannot represent a non boolean value: ""'
      }
    }
  ]

**Comment by HRT-Tech** [comment]
Problem can be resolved by setting SIGN_IN_PREFILLED=false in .env file.

**Comment by curiousercreative** [comment]
For me, the below was the specific error message, but this suggestion resolved it.
>Error: Boolean cannot represent a non boolean value: ""
